
from pysb import *

Model()

Monomer('CIA_1', ['state'], {'state': ['0', '1']})
Monomer('CIA_2', ['state'], {'state': ['0', '1']})
Monomer('CIA_3', ['state'], {'state': ['0', '1']})
Monomer('CIA_4', ['state'], {'state': ['0', '1']})
Monomer('CIR_1', ['state'], {'state': ['0', '1']})
Monomer('CIR_2', ['state'], {'state': ['0', '1']})
Monomer('CIR_3', ['state'], {'state': ['0', '1']})
Monomer('CIR_4', ['state'], {'state': ['0', '1']})
Monomer('CI_1', ['state'], {'state': ['0', '1']})
Monomer('CI_2', ['state'], {'state': ['0', '1']})
Monomer('CI_3', ['state'], {'state': ['0', '1']})
Monomer('CI_4', ['state'], {'state': ['0', '1']})
Monomer('EN_1', ['state'], {'state': ['0', '1']})
Monomer('EN_2', ['state'], {'state': ['0', '1']})
Monomer('EN_3', ['state'], {'state': ['0', '1']})
Monomer('EN_4', ['state'], {'state': ['0', '1']})
Monomer('HH_1', ['state'], {'state': ['0', '1']})
Monomer('HH_2', ['state'], {'state': ['0', '1']})
Monomer('HH_3', ['state'], {'state': ['0', '1']})
Monomer('HH_4', ['state'], {'state': ['0', '1']})
Monomer('PH_1', ['state'], {'state': ['0', '1']})
Monomer('PH_2', ['state'], {'state': ['0', '1']})
Monomer('PH_3', ['state'], {'state': ['0', '1']})
Monomer('PH_4', ['state'], {'state': ['0', '1']})
Monomer('PTC_1', ['state'], {'state': ['0', '1']})
Monomer('PTC_2', ['state'], {'state': ['0', '1']})
Monomer('PTC_3', ['state'], {'state': ['0', '1']})
Monomer('PTC_4', ['state'], {'state': ['0', '1']})
Monomer('SLP_1', ['state'], {'state': ['0', '1']})
Monomer('SLP_2', ['state'], {'state': ['0', '1']})
Monomer('SLP_3', ['state'], {'state': ['0', '1']})
Monomer('SLP_4', ['state'], {'state': ['0', '1']})
Monomer('SMO_1', ['state'], {'state': ['0', '1']})
Monomer('SMO_2', ['state'], {'state': ['0', '1']})
Monomer('SMO_3', ['state'], {'state': ['0', '1']})
Monomer('SMO_4', ['state'], {'state': ['0', '1']})
Monomer('WG_1', ['state'], {'state': ['0', '1']})
Monomer('WG_2', ['state'], {'state': ['0', '1']})
Monomer('WG_3', ['state'], {'state': ['0', '1']})
Monomer('WG_4', ['state'], {'state': ['0', '1']})
Monomer('ci_mRNA_1', ['state'], {'state': ['0', '1']})
Monomer('ci_mRNA_2', ['state'], {'state': ['0', '1']})
Monomer('ci_mRNA_3', ['state'], {'state': ['0', '1']})
Monomer('ci_mRNA_4', ['state'], {'state': ['0', '1']})
Monomer('en_mRNA_1', ['state'], {'state': ['0', '1']})
Monomer('en_mRNA_2', ['state'], {'state': ['0', '1']})
Monomer('en_mRNA_3', ['state'], {'state': ['0', '1']})
Monomer('en_mRNA_4', ['state'], {'state': ['0', '1']})
Monomer('hh_mRNA_1', ['state'], {'state': ['0', '1']})
Monomer('hh_mRNA_2', ['state'], {'state': ['0', '1']})
Monomer('hh_mRNA_3', ['state'], {'state': ['0', '1']})
Monomer('hh_mRNA_4', ['state'], {'state': ['0', '1']})
Monomer('ptc_mRNA_1', ['state'], {'state': ['0', '1']})
Monomer('ptc_mRNA_2', ['state'], {'state': ['0', '1']})
Monomer('ptc_mRNA_3', ['state'], {'state': ['0', '1']})
Monomer('ptc_mRNA_4', ['state'], {'state': ['0', '1']})
Monomer('wg_mRNA_1', ['state'], {'state': ['0', '1']})
Monomer('wg_mRNA_2', ['state'], {'state': ['0', '1']})
Monomer('wg_mRNA_3', ['state'], {'state': ['0', '1']})
Monomer('wg_mRNA_4', ['state'], {'state': ['0', '1']})

Initial(CIA_1(state = '0'), Parameter('CIA_10_init', 1))
Initial(CIA_1(state = '1'), Parameter('CIA_11_init', 0))
Initial(CIA_2(state = '0'), Parameter('CIA_20_init', 1))
Initial(CIA_2(state = '1'), Parameter('CIA_21_init', 0))
Initial(CIA_3(state = '0'), Parameter('CIA_30_init', 1))
Initial(CIA_3(state = '1'), Parameter('CIA_31_init', 0))
Initial(CIA_4(state = '0'), Parameter('CIA_40_init', 1))
Initial(CIA_4(state = '1'), Parameter('CIA_41_init', 0))
Initial(CIR_1(state = '0'), Parameter('CIR_10_init', 1))
Initial(CIR_1(state = '1'), Parameter('CIR_11_init', 0))
Initial(CIR_2(state = '0'), Parameter('CIR_20_init', 1))
Initial(CIR_2(state = '1'), Parameter('CIR_21_init', 0))
Initial(CIR_3(state = '0'), Parameter('CIR_30_init', 1))
Initial(CIR_3(state = '1'), Parameter('CIR_31_init', 0))
Initial(CIR_4(state = '0'), Parameter('CIR_40_init', 1))
Initial(CIR_4(state = '1'), Parameter('CIR_41_init', 0))
Initial(CI_1(state = '0'), Parameter('CI_10_init', 1))
Initial(CI_1(state = '1'), Parameter('CI_11_init', 0))
Initial(CI_2(state = '0'), Parameter('CI_20_init', 1))
Initial(CI_2(state = '1'), Parameter('CI_21_init', 0))
Initial(CI_3(state = '0'), Parameter('CI_30_init', 1))
Initial(CI_3(state = '1'), Parameter('CI_31_init', 0))
Initial(CI_4(state = '0'), Parameter('CI_40_init', 1))
Initial(CI_4(state = '1'), Parameter('CI_41_init', 0))
Initial(EN_1(state = '0'), Parameter('EN_10_init', 1))
Initial(EN_1(state = '1'), Parameter('EN_11_init', 0))
Initial(EN_2(state = '0'), Parameter('EN_20_init', 1))
Initial(EN_2(state = '1'), Parameter('EN_21_init', 0))
Initial(EN_3(state = '0'), Parameter('EN_30_init', 1))
Initial(EN_3(state = '1'), Parameter('EN_31_init', 0))
Initial(EN_4(state = '0'), Parameter('EN_40_init', 1))
Initial(EN_4(state = '1'), Parameter('EN_41_init', 0))
Initial(HH_1(state = '0'), Parameter('HH_10_init', 1))
Initial(HH_1(state = '1'), Parameter('HH_11_init', 0))
Initial(HH_2(state = '0'), Parameter('HH_20_init', 1))
Initial(HH_2(state = '1'), Parameter('HH_21_init', 0))
Initial(HH_3(state = '0'), Parameter('HH_30_init', 1))
Initial(HH_3(state = '1'), Parameter('HH_31_init', 0))
Initial(HH_4(state = '0'), Parameter('HH_40_init', 1))
Initial(HH_4(state = '1'), Parameter('HH_41_init', 0))
Initial(PH_1(state = '0'), Parameter('PH_10_init', 1))
Initial(PH_1(state = '1'), Parameter('PH_11_init', 0))
Initial(PH_2(state = '0'), Parameter('PH_20_init', 1))
Initial(PH_2(state = '1'), Parameter('PH_21_init', 0))
Initial(PH_3(state = '0'), Parameter('PH_30_init', 1))
Initial(PH_3(state = '1'), Parameter('PH_31_init', 0))
Initial(PH_4(state = '0'), Parameter('PH_40_init', 1))
Initial(PH_4(state = '1'), Parameter('PH_41_init', 0))
Initial(PTC_1(state = '0'), Parameter('PTC_10_init', 1))
Initial(PTC_1(state = '1'), Parameter('PTC_11_init', 0))
Initial(PTC_2(state = '0'), Parameter('PTC_20_init', 1))
Initial(PTC_2(state = '1'), Parameter('PTC_21_init', 0))
Initial(PTC_3(state = '0'), Parameter('PTC_30_init', 1))
Initial(PTC_3(state = '1'), Parameter('PTC_31_init', 0))
Initial(PTC_4(state = '0'), Parameter('PTC_40_init', 1))
Initial(PTC_4(state = '1'), Parameter('PTC_41_init', 0))
Initial(SLP_1(state = '0'), Parameter('SLP_10_init', 1))
Initial(SLP_1(state = '1'), Parameter('SLP_11_init', 0))
Initial(SLP_2(state = '0'), Parameter('SLP_20_init', 1))
Initial(SLP_2(state = '1'), Parameter('SLP_21_init', 0))
Initial(SLP_3(state = '0'), Parameter('SLP_30_init', 0))
Initial(SLP_3(state = '1'), Parameter('SLP_31_init', 1))
Initial(SLP_4(state = '0'), Parameter('SLP_40_init', 0))
Initial(SLP_4(state = '1'), Parameter('SLP_41_init', 1))
Initial(SMO_1(state = '0'), Parameter('SMO_10_init', 1))
Initial(SMO_1(state = '1'), Parameter('SMO_11_init', 0))
Initial(SMO_2(state = '0'), Parameter('SMO_20_init', 1))
Initial(SMO_2(state = '1'), Parameter('SMO_21_init', 0))
Initial(SMO_3(state = '0'), Parameter('SMO_30_init', 1))
Initial(SMO_3(state = '1'), Parameter('SMO_31_init', 0))
Initial(SMO_4(state = '0'), Parameter('SMO_40_init', 1))
Initial(SMO_4(state = '1'), Parameter('SMO_41_init', 0))
Initial(WG_1(state = '0'), Parameter('WG_10_init', 1))
Initial(WG_1(state = '1'), Parameter('WG_11_init', 0))
Initial(WG_2(state = '0'), Parameter('WG_20_init', 1))
Initial(WG_2(state = '1'), Parameter('WG_21_init', 0))
Initial(WG_3(state = '0'), Parameter('WG_30_init', 1))
Initial(WG_3(state = '1'), Parameter('WG_31_init', 0))
Initial(WG_4(state = '0'), Parameter('WG_40_init', 1))
Initial(WG_4(state = '1'), Parameter('WG_41_init', 0))
Initial(ci_mRNA_1(state = '0'), Parameter('ci_mRNA_10_init', 1))
Initial(ci_mRNA_1(state = '1'), Parameter('ci_mRNA_11_init', 0))
Initial(ci_mRNA_2(state = '0'), Parameter('ci_mRNA_20_init', 0))
Initial(ci_mRNA_2(state = '1'), Parameter('ci_mRNA_21_init', 1))
Initial(ci_mRNA_3(state = '0'), Parameter('ci_mRNA_30_init', 0))
Initial(ci_mRNA_3(state = '1'), Parameter('ci_mRNA_31_init', 1))
Initial(ci_mRNA_4(state = '0'), Parameter('ci_mRNA_40_init', 0))
Initial(ci_mRNA_4(state = '1'), Parameter('ci_mRNA_41_init', 1))
Initial(en_mRNA_1(state = '0'), Parameter('en_mRNA_10_init', 0))
Initial(en_mRNA_1(state = '1'), Parameter('en_mRNA_11_init', 1))
Initial(en_mRNA_2(state = '0'), Parameter('en_mRNA_20_init', 1))
Initial(en_mRNA_2(state = '1'), Parameter('en_mRNA_21_init', 0))
Initial(en_mRNA_3(state = '0'), Parameter('en_mRNA_30_init', 1))
Initial(en_mRNA_3(state = '1'), Parameter('en_mRNA_31_init', 0))
Initial(en_mRNA_4(state = '0'), Parameter('en_mRNA_40_init', 1))
Initial(en_mRNA_4(state = '1'), Parameter('en_mRNA_41_init', 0))
Initial(hh_mRNA_1(state = '0'), Parameter('hh_mRNA_10_init', 0))
Initial(hh_mRNA_1(state = '1'), Parameter('hh_mRNA_11_init', 1))
Initial(hh_mRNA_2(state = '0'), Parameter('hh_mRNA_20_init', 1))
Initial(hh_mRNA_2(state = '1'), Parameter('hh_mRNA_21_init', 0))
Initial(hh_mRNA_3(state = '0'), Parameter('hh_mRNA_30_init', 1))
Initial(hh_mRNA_3(state = '1'), Parameter('hh_mRNA_31_init', 0))
Initial(hh_mRNA_4(state = '0'), Parameter('hh_mRNA_40_init', 1))
Initial(hh_mRNA_4(state = '1'), Parameter('hh_mRNA_41_init', 0))
Initial(ptc_mRNA_1(state = '0'), Parameter('ptc_mRNA_10_init', 1))
Initial(ptc_mRNA_1(state = '1'), Parameter('ptc_mRNA_11_init', 0))
Initial(ptc_mRNA_2(state = '0'), Parameter('ptc_mRNA_20_init', 0))
Initial(ptc_mRNA_2(state = '1'), Parameter('ptc_mRNA_21_init', 1))
Initial(ptc_mRNA_3(state = '0'), Parameter('ptc_mRNA_30_init', 0))
Initial(ptc_mRNA_3(state = '1'), Parameter('ptc_mRNA_31_init', 1))
Initial(ptc_mRNA_4(state = '0'), Parameter('ptc_mRNA_40_init', 0))
Initial(ptc_mRNA_4(state = '1'), Parameter('ptc_mRNA_41_init', 1))
Initial(wg_mRNA_1(state = '0'), Parameter('wg_mRNA_10_init', 1))
Initial(wg_mRNA_1(state = '1'), Parameter('wg_mRNA_11_init', 0))
Initial(wg_mRNA_2(state = '0'), Parameter('wg_mRNA_20_init', 1))
Initial(wg_mRNA_2(state = '1'), Parameter('wg_mRNA_21_init', 0))
Initial(wg_mRNA_3(state = '0'), Parameter('wg_mRNA_30_init', 1))
Initial(wg_mRNA_3(state = '1'), Parameter('wg_mRNA_31_init', 0))
Initial(wg_mRNA_4(state = '0'), Parameter('wg_mRNA_40_init', 0))
Initial(wg_mRNA_4(state = '1'), Parameter('wg_mRNA_41_init', 1))

Observable('CIA_10_obs', CIA_1(state = '0'))
Observable('CIA_11_obs', CIA_1(state = '1'))
Observable('CIA_20_obs', CIA_2(state = '0'))
Observable('CIA_21_obs', CIA_2(state = '1'))
Observable('CIA_30_obs', CIA_3(state = '0'))
Observable('CIA_31_obs', CIA_3(state = '1'))
Observable('CIA_40_obs', CIA_4(state = '0'))
Observable('CIA_41_obs', CIA_4(state = '1'))
Observable('CIR_10_obs', CIR_1(state = '0'))
Observable('CIR_11_obs', CIR_1(state = '1'))
Observable('CIR_20_obs', CIR_2(state = '0'))
Observable('CIR_21_obs', CIR_2(state = '1'))
Observable('CIR_30_obs', CIR_3(state = '0'))
Observable('CIR_31_obs', CIR_3(state = '1'))
Observable('CIR_40_obs', CIR_4(state = '0'))
Observable('CIR_41_obs', CIR_4(state = '1'))
Observable('CI_10_obs', CI_1(state = '0'))
Observable('CI_11_obs', CI_1(state = '1'))
Observable('CI_20_obs', CI_2(state = '0'))
Observable('CI_21_obs', CI_2(state = '1'))
Observable('CI_30_obs', CI_3(state = '0'))
Observable('CI_31_obs', CI_3(state = '1'))
Observable('CI_40_obs', CI_4(state = '0'))
Observable('CI_41_obs', CI_4(state = '1'))
Observable('EN_10_obs', EN_1(state = '0'))
Observable('EN_11_obs', EN_1(state = '1'))
Observable('EN_20_obs', EN_2(state = '0'))
Observable('EN_21_obs', EN_2(state = '1'))
Observable('EN_30_obs', EN_3(state = '0'))
Observable('EN_31_obs', EN_3(state = '1'))
Observable('EN_40_obs', EN_4(state = '0'))
Observable('EN_41_obs', EN_4(state = '1'))
Observable('HH_10_obs', HH_1(state = '0'))
Observable('HH_11_obs', HH_1(state = '1'))
Observable('HH_20_obs', HH_2(state = '0'))
Observable('HH_21_obs', HH_2(state = '1'))
Observable('HH_30_obs', HH_3(state = '0'))
Observable('HH_31_obs', HH_3(state = '1'))
Observable('HH_40_obs', HH_4(state = '0'))
Observable('HH_41_obs', HH_4(state = '1'))
Observable('PH_10_obs', PH_1(state = '0'))
Observable('PH_11_obs', PH_1(state = '1'))
Observable('PH_20_obs', PH_2(state = '0'))
Observable('PH_21_obs', PH_2(state = '1'))
Observable('PH_30_obs', PH_3(state = '0'))
Observable('PH_31_obs', PH_3(state = '1'))
Observable('PH_40_obs', PH_4(state = '0'))
Observable('PH_41_obs', PH_4(state = '1'))
Observable('PTC_10_obs', PTC_1(state = '0'))
Observable('PTC_11_obs', PTC_1(state = '1'))
Observable('PTC_20_obs', PTC_2(state = '0'))
Observable('PTC_21_obs', PTC_2(state = '1'))
Observable('PTC_30_obs', PTC_3(state = '0'))
Observable('PTC_31_obs', PTC_3(state = '1'))
Observable('PTC_40_obs', PTC_4(state = '0'))
Observable('PTC_41_obs', PTC_4(state = '1'))
Observable('SLP_10_obs', SLP_1(state = '0'))
Observable('SLP_11_obs', SLP_1(state = '1'))
Observable('SLP_20_obs', SLP_2(state = '0'))
Observable('SLP_21_obs', SLP_2(state = '1'))
Observable('SLP_30_obs', SLP_3(state = '0'))
Observable('SLP_31_obs', SLP_3(state = '1'))
Observable('SLP_40_obs', SLP_4(state = '0'))
Observable('SLP_41_obs', SLP_4(state = '1'))
Observable('SMO_10_obs', SMO_1(state = '0'))
Observable('SMO_11_obs', SMO_1(state = '1'))
Observable('SMO_20_obs', SMO_2(state = '0'))
Observable('SMO_21_obs', SMO_2(state = '1'))
Observable('SMO_30_obs', SMO_3(state = '0'))
Observable('SMO_31_obs', SMO_3(state = '1'))
Observable('SMO_40_obs', SMO_4(state = '0'))
Observable('SMO_41_obs', SMO_4(state = '1'))
Observable('WG_10_obs', WG_1(state = '0'))
Observable('WG_11_obs', WG_1(state = '1'))
Observable('WG_20_obs', WG_2(state = '0'))
Observable('WG_21_obs', WG_2(state = '1'))
Observable('WG_30_obs', WG_3(state = '0'))
Observable('WG_31_obs', WG_3(state = '1'))
Observable('WG_40_obs', WG_4(state = '0'))
Observable('WG_41_obs', WG_4(state = '1'))
Observable('ci_mRNA_10_obs', ci_mRNA_1(state = '0'))
Observable('ci_mRNA_11_obs', ci_mRNA_1(state = '1'))
Observable('ci_mRNA_20_obs', ci_mRNA_2(state = '0'))
Observable('ci_mRNA_21_obs', ci_mRNA_2(state = '1'))
Observable('ci_mRNA_30_obs', ci_mRNA_3(state = '0'))
Observable('ci_mRNA_31_obs', ci_mRNA_3(state = '1'))
Observable('ci_mRNA_40_obs', ci_mRNA_4(state = '0'))
Observable('ci_mRNA_41_obs', ci_mRNA_4(state = '1'))
Observable('en_mRNA_10_obs', en_mRNA_1(state = '0'))
Observable('en_mRNA_11_obs', en_mRNA_1(state = '1'))
Observable('en_mRNA_20_obs', en_mRNA_2(state = '0'))
Observable('en_mRNA_21_obs', en_mRNA_2(state = '1'))
Observable('en_mRNA_30_obs', en_mRNA_3(state = '0'))
Observable('en_mRNA_31_obs', en_mRNA_3(state = '1'))
Observable('en_mRNA_40_obs', en_mRNA_4(state = '0'))
Observable('en_mRNA_41_obs', en_mRNA_4(state = '1'))
Observable('hh_mRNA_10_obs', hh_mRNA_1(state = '0'))
Observable('hh_mRNA_11_obs', hh_mRNA_1(state = '1'))
Observable('hh_mRNA_20_obs', hh_mRNA_2(state = '0'))
Observable('hh_mRNA_21_obs', hh_mRNA_2(state = '1'))
Observable('hh_mRNA_30_obs', hh_mRNA_3(state = '0'))
Observable('hh_mRNA_31_obs', hh_mRNA_3(state = '1'))
Observable('hh_mRNA_40_obs', hh_mRNA_4(state = '0'))
Observable('hh_mRNA_41_obs', hh_mRNA_4(state = '1'))
Observable('ptc_mRNA_10_obs', ptc_mRNA_1(state = '0'))
Observable('ptc_mRNA_11_obs', ptc_mRNA_1(state = '1'))
Observable('ptc_mRNA_20_obs', ptc_mRNA_2(state = '0'))
Observable('ptc_mRNA_21_obs', ptc_mRNA_2(state = '1'))
Observable('ptc_mRNA_30_obs', ptc_mRNA_3(state = '0'))
Observable('ptc_mRNA_31_obs', ptc_mRNA_3(state = '1'))
Observable('ptc_mRNA_40_obs', ptc_mRNA_4(state = '0'))
Observable('ptc_mRNA_41_obs', ptc_mRNA_4(state = '1'))
Observable('wg_mRNA_10_obs', wg_mRNA_1(state = '0'))
Observable('wg_mRNA_11_obs', wg_mRNA_1(state = '1'))
Observable('wg_mRNA_20_obs', wg_mRNA_2(state = '0'))
Observable('wg_mRNA_21_obs', wg_mRNA_2(state = '1'))
Observable('wg_mRNA_30_obs', wg_mRNA_3(state = '0'))
Observable('wg_mRNA_31_obs', wg_mRNA_3(state = '1'))
Observable('wg_mRNA_40_obs', wg_mRNA_4(state = '0'))
Observable('wg_mRNA_41_obs', wg_mRNA_4(state = '1'))

Rule('wg_mRNA_31', wg_mRNA_3(state = '1') + CIR_3(state = '1') >> wg_mRNA_3(state = '0') + CIR_3(state = '1'), on)
Rule('wg_mRNA_34', CIR_3(state = '0') + wg_mRNA_3(state = '1') + SLP_3(state = '0') + CIA_3(state = '0') >> CIR_3(state = '0') + wg_mRNA_3(state = '0') + SLP_3(state = '0') + CIA_3(state = '0'), on)
Rule('wg_mRNA_35', CIR_3(state = '0') + wg_mRNA_3(state = '0') + SLP_3(state = '1') + CIA_3(state = '1') >> CIR_3(state = '0') + wg_mRNA_3(state = '1') + SLP_3(state = '1') + CIA_3(state = '1'), on)

Rule('wg_mRNA_21', wg_mRNA_2(state = '1') + CIR_2(state = '1') >> wg_mRNA_2(state = '0') + CIR_2(state = '1'), on)
Rule('wg_mRNA_24', CIR_2(state = '0') + wg_mRNA_2(state = '1') + SLP_2(state = '0') + CIA_2(state = '0') >> CIR_2(state = '0') + wg_mRNA_2(state = '0') + SLP_2(state = '0') + CIA_2(state = '0'), on)
Rule('wg_mRNA_25', CIR_2(state = '0') + wg_mRNA_2(state = '0') + SLP_2(state = '1') + CIA_2(state = '1') >> CIR_2(state = '0') + wg_mRNA_2(state = '1') + SLP_2(state = '1') + CIA_2(state = '1'), on)

Rule('PTC_11', PTC_1(state = '0') + ptc_mRNA_1(state = '1') >> PTC_1(state = '1') + ptc_mRNA_1(state = '1'), on)
Rule('PTC_12', ptc_mRNA_1(state = '0') + PTC_1(state = '1') + HH_2(state = '1') >> ptc_mRNA_1(state = '0') + PTC_1(state = '0') + HH_2(state = '1'), on)
Rule('PTC_13', ptc_mRNA_1(state = '0') + PTC_1(state = '1') + HH_2(state = '0') + HH_4(state = '1') >> ptc_mRNA_1(state = '0') + PTC_1(state = '0') + HH_2(state = '0') + HH_4(state = '1'), on)

Rule('CI_21', CI_2(state = '0') + ci_mRNA_2(state = '1') >> CI_2(state = '1') + ci_mRNA_2(state = '1'), on)
Rule('CI_22', CI_2(state = '1') + ci_mRNA_2(state = '0') >> CI_2(state = '0') + ci_mRNA_2(state = '0'), on)

Rule('ci_mRNA_11', ci_mRNA_1(state = '1') + EN_1(state = '1') >> ci_mRNA_1(state = '0') + EN_1(state = '1'), on)
Rule('ci_mRNA_12', ci_mRNA_1(state = '0') + EN_1(state = '0') >> ci_mRNA_1(state = '1') + EN_1(state = '0'), on)

Rule('ci_mRNA_31', ci_mRNA_3(state = '1') + EN_3(state = '1') >> ci_mRNA_3(state = '0') + EN_3(state = '1'), on)
Rule('ci_mRNA_32', ci_mRNA_3(state = '0') + EN_3(state = '0') >> ci_mRNA_3(state = '1') + EN_3(state = '0'), on)

Rule('PTC_21', PTC_2(state = '0') + ptc_mRNA_2(state = '1') >> PTC_2(state = '1') + ptc_mRNA_2(state = '1'), on)
Rule('PTC_22', PTC_2(state = '1') + ptc_mRNA_2(state = '0') + HH_1(state = '1') >> PTC_2(state = '0') + ptc_mRNA_2(state = '0') + HH_1(state = '1'), on)
Rule('PTC_23', ptc_mRNA_2(state = '0') + HH_1(state = '0') + PTC_2(state = '1') + HH_3(state = '1') >> ptc_mRNA_2(state = '0') + HH_1(state = '0') + PTC_2(state = '0') + HH_3(state = '1'), on)

Rule('wg_mRNA_11', wg_mRNA_1(state = '1') + CIR_1(state = '1') >> wg_mRNA_1(state = '0') + CIR_1(state = '1'), on)
Rule('wg_mRNA_14', CIR_1(state = '0') + wg_mRNA_1(state = '1') + SLP_1(state = '0') + CIA_1(state = '0') >> CIR_1(state = '0') + wg_mRNA_1(state = '0') + SLP_1(state = '0') + CIA_1(state = '0'), on)
Rule('wg_mRNA_15', CIR_1(state = '0') + wg_mRNA_1(state = '0') + SLP_1(state = '1') + CIA_1(state = '1') >> CIR_1(state = '0') + wg_mRNA_1(state = '1') + SLP_1(state = '1') + CIA_1(state = '1'), on)

Rule('PTC_31', PTC_3(state = '0') + ptc_mRNA_3(state = '1') >> PTC_3(state = '1') + ptc_mRNA_3(state = '1'), on)
Rule('PTC_32', PTC_3(state = '1') + ptc_mRNA_3(state = '0') + HH_2(state = '1') >> PTC_3(state = '0') + ptc_mRNA_3(state = '0') + HH_2(state = '1'), on)
Rule('PTC_33', ptc_mRNA_3(state = '0') + HH_2(state = '0') + PTC_3(state = '1') + HH_4(state = '1') >> ptc_mRNA_3(state = '0') + HH_2(state = '0') + PTC_3(state = '0') + HH_4(state = '1'), on)

Rule('PH_11', PH_1(state = '0') + ptc_mRNA_1(state = '1') + hh_mRNA_2(state = '1') >> PH_1(state = '1') + ptc_mRNA_1(state = '1') + hh_mRNA_2(state = '1'), on)
Rule('PH_12', PH_1(state = '0') + ptc_mRNA_1(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '1') >> PH_1(state = '1') + ptc_mRNA_1(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '1'), on)
Rule('PH_13', PH_1(state = '1') + ptc_mRNA_1(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0') >> PH_1(state = '0') + ptc_mRNA_1(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0'), on)
Rule('PH_14', PH_1(state = '1') + ptc_mRNA_1(state = '0') + HH_2(state = '1') >> PH_1(state = '0') + ptc_mRNA_1(state = '0') + HH_2(state = '1'), on)
Rule('PH_15', PH_1(state = '1') + ptc_mRNA_1(state = '0') + HH_2(state = '0') + PTC_1(state = '1') + HH_4(state = '1') >> PH_1(state = '0') + ptc_mRNA_1(state = '0') + HH_2(state = '0') + PTC_1(state = '1') + HH_4(state = '1'), on)
Rule('PH_16', PH_1(state = '0') + ptc_mRNA_1(state = '0') + HH_2(state = '0') + PTC_1(state = '1') + HH_4(state = '0') + hh_mRNA_2(state = '1') >> PH_1(state = '1') + ptc_mRNA_1(state = '0') + HH_2(state = '0') + PTC_1(state = '1') + HH_4(state = '0') + hh_mRNA_2(state = '1'), on)
Rule('PH_17', PH_1(state = '0') + ptc_mRNA_1(state = '0') + HH_2(state = '0') + PTC_1(state = '1') + HH_4(state = '0') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '1') >> PH_1(state = '1') + ptc_mRNA_1(state = '0') + HH_2(state = '0') + PTC_1(state = '1') + HH_4(state = '0') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '1'), on)
Rule('PH_18', PH_1(state = '1') + ptc_mRNA_1(state = '0') + HH_2(state = '0') + PTC_1(state = '1') + HH_4(state = '0') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0') >> PH_1(state = '0') + ptc_mRNA_1(state = '0') + HH_2(state = '0') + PTC_1(state = '1') + HH_4(state = '0') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0'), on)
Rule('PH_19', PH_1(state = '1') + ptc_mRNA_1(state = '0') + HH_2(state = '0') + PTC_1(state = '0') >> PH_1(state = '0') + ptc_mRNA_1(state = '0') + HH_2(state = '0') + PTC_1(state = '0'), on)

Rule('PH_31', PH_3(state = '0') + ptc_mRNA_3(state = '1') + hh_mRNA_2(state = '1') >> PH_3(state = '1') + ptc_mRNA_3(state = '1') + hh_mRNA_2(state = '1'), on)
Rule('PH_32', PH_3(state = '0') + ptc_mRNA_3(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '1') >> PH_3(state = '1') + ptc_mRNA_3(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '1'), on)
Rule('PH_33', PH_3(state = '1') + ptc_mRNA_3(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0') >> PH_3(state = '0') + ptc_mRNA_3(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0'), on)
Rule('PH_34', PH_3(state = '1') + ptc_mRNA_3(state = '0') + HH_4(state = '1') >> PH_3(state = '0') + ptc_mRNA_3(state = '0') + HH_4(state = '1'), on)
Rule('PH_35', PH_3(state = '1') + ptc_mRNA_3(state = '0') + HH_4(state = '0') + HH_2(state = '1') >> PH_3(state = '0') + ptc_mRNA_3(state = '0') + HH_4(state = '0') + HH_2(state = '1'), on)
Rule('PH_36', PH_3(state = '0') + ptc_mRNA_3(state = '0') + HH_4(state = '0') + HH_2(state = '0') + PTC_3(state = '1') + hh_mRNA_2(state = '1') >> PH_3(state = '1') + ptc_mRNA_3(state = '0') + HH_4(state = '0') + HH_2(state = '0') + PTC_3(state = '1') + hh_mRNA_2(state = '1'), on)
Rule('PH_37', PH_3(state = '0') + ptc_mRNA_3(state = '0') + HH_4(state = '0') + HH_2(state = '0') + PTC_3(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '1') >> PH_3(state = '1') + ptc_mRNA_3(state = '0') + HH_4(state = '0') + HH_2(state = '0') + PTC_3(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '1'), on)
Rule('PH_38', PH_3(state = '1') + ptc_mRNA_3(state = '0') + HH_4(state = '0') + HH_2(state = '0') + PTC_3(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0') >> PH_3(state = '0') + ptc_mRNA_3(state = '0') + HH_4(state = '0') + HH_2(state = '0') + PTC_3(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0'), on)
Rule('PH_39', PH_3(state = '1') + ptc_mRNA_3(state = '0') + HH_4(state = '0') + HH_2(state = '0') + PTC_3(state = '0') >> PH_3(state = '0') + ptc_mRNA_3(state = '0') + HH_4(state = '0') + HH_2(state = '0') + PTC_3(state = '0'), on)

Rule('PH_21', PH_2(state = '0') + ptc_mRNA_2(state = '1') + hh_mRNA_1(state = '1') >> PH_2(state = '1') + ptc_mRNA_2(state = '1') + hh_mRNA_1(state = '1'), on)
Rule('PH_22', PH_2(state = '0') + ptc_mRNA_2(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '1') >> PH_2(state = '1') + ptc_mRNA_2(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '1'), on)
Rule('PH_23', PH_2(state = '1') + ptc_mRNA_2(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') >> PH_2(state = '0') + ptc_mRNA_2(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0'), on)
Rule('PH_24', PH_2(state = '1') + ptc_mRNA_2(state = '0') + HH_3(state = '1') >> PH_2(state = '0') + ptc_mRNA_2(state = '0') + HH_3(state = '1'), on)
Rule('PH_25', PH_2(state = '1') + ptc_mRNA_2(state = '0') + HH_3(state = '0') + HH_1(state = '1') >> PH_2(state = '0') + ptc_mRNA_2(state = '0') + HH_3(state = '0') + HH_1(state = '1'), on)
Rule('PH_26', PH_2(state = '0') + ptc_mRNA_2(state = '0') + HH_3(state = '0') + HH_1(state = '0') + PTC_2(state = '1') + hh_mRNA_1(state = '1') >> PH_2(state = '1') + ptc_mRNA_2(state = '0') + HH_3(state = '0') + HH_1(state = '0') + PTC_2(state = '1') + hh_mRNA_1(state = '1'), on)
Rule('PH_27', PH_2(state = '0') + ptc_mRNA_2(state = '0') + HH_3(state = '0') + HH_1(state = '0') + PTC_2(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '1') >> PH_2(state = '1') + ptc_mRNA_2(state = '0') + HH_3(state = '0') + HH_1(state = '0') + PTC_2(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '1'), on)
Rule('PH_28', PH_2(state = '1') + ptc_mRNA_2(state = '0') + HH_3(state = '0') + HH_1(state = '0') + PTC_2(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') >> PH_2(state = '0') + ptc_mRNA_2(state = '0') + HH_3(state = '0') + HH_1(state = '0') + PTC_2(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0'), on)
Rule('PH_29', PH_2(state = '1') + ptc_mRNA_2(state = '0') + HH_3(state = '0') + HH_1(state = '0') + PTC_2(state = '0') >> PH_2(state = '0') + ptc_mRNA_2(state = '0') + HH_3(state = '0') + HH_1(state = '0') + PTC_2(state = '0'), on)

Rule('PH_41', PH_4(state = '0') + ptc_mRNA_4(state = '1') + hh_mRNA_1(state = '1') >> PH_4(state = '1') + ptc_mRNA_4(state = '1') + hh_mRNA_1(state = '1'), on)
Rule('PH_42', PH_4(state = '0') + ptc_mRNA_4(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '1') >> PH_4(state = '1') + ptc_mRNA_4(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '1'), on)
Rule('PH_43', PH_4(state = '1') + ptc_mRNA_4(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') >> PH_4(state = '0') + ptc_mRNA_4(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0'), on)
Rule('PH_44', PH_4(state = '1') + ptc_mRNA_4(state = '0') + PTC_4(state = '1') + HH_1(state = '1') >> PH_4(state = '0') + ptc_mRNA_4(state = '0') + PTC_4(state = '1') + HH_1(state = '1'), on)
Rule('PH_45', PH_4(state = '1') + ptc_mRNA_4(state = '0') + PTC_4(state = '1') + HH_1(state = '0') + HH_3(state = '1') >> PH_4(state = '0') + ptc_mRNA_4(state = '0') + PTC_4(state = '1') + HH_1(state = '0') + HH_3(state = '1'), on)
Rule('PH_46', PH_4(state = '0') + ptc_mRNA_4(state = '0') + PTC_4(state = '1') + HH_1(state = '0') + HH_3(state = '0') + hh_mRNA_1(state = '1') >> PH_4(state = '1') + ptc_mRNA_4(state = '0') + PTC_4(state = '1') + HH_1(state = '0') + HH_3(state = '0') + hh_mRNA_1(state = '1'), on)
Rule('PH_47', PH_4(state = '0') + ptc_mRNA_4(state = '0') + PTC_4(state = '1') + HH_1(state = '0') + HH_3(state = '0') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '1') >> PH_4(state = '1') + ptc_mRNA_4(state = '0') + PTC_4(state = '1') + HH_1(state = '0') + HH_3(state = '0') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '1'), on)
Rule('PH_48', PH_4(state = '1') + ptc_mRNA_4(state = '0') + PTC_4(state = '1') + HH_1(state = '0') + HH_3(state = '0') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') >> PH_4(state = '0') + ptc_mRNA_4(state = '0') + PTC_4(state = '1') + HH_1(state = '0') + HH_3(state = '0') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0'), on)
Rule('PH_49', PH_4(state = '1') + ptc_mRNA_4(state = '0') + PTC_4(state = '0') >> PH_4(state = '0') + ptc_mRNA_4(state = '0') + PTC_4(state = '0'), on)

Rule('SMO_31', SMO_3(state = '0') + hh_mRNA_4(state = '1') >> SMO_3(state = '1') + hh_mRNA_4(state = '1'), on)
Rule('SMO_32', SMO_3(state = '0') + hh_mRNA_4(state = '0') + hh_mRNA_2(state = '1') >> SMO_3(state = '1') + hh_mRNA_4(state = '0') + hh_mRNA_2(state = '1'), on)
Rule('SMO_33', SMO_3(state = '1') + hh_mRNA_4(state = '0') + hh_mRNA_2(state = '0') + ptc_mRNA_3(state = '1') >> SMO_3(state = '0') + hh_mRNA_4(state = '0') + hh_mRNA_2(state = '0') + ptc_mRNA_3(state = '1'), on)
Rule('SMO_34', SMO_3(state = '0') + hh_mRNA_4(state = '0') + hh_mRNA_2(state = '0') + ptc_mRNA_3(state = '0') + PTC_3(state = '1') + HH_2(state = '1') >> SMO_3(state = '1') + hh_mRNA_4(state = '0') + hh_mRNA_2(state = '0') + ptc_mRNA_3(state = '0') + PTC_3(state = '1') + HH_2(state = '1'), on)
Rule('SMO_35', SMO_3(state = '0') + hh_mRNA_4(state = '0') + hh_mRNA_2(state = '0') + ptc_mRNA_3(state = '0') + PTC_3(state = '1') + HH_2(state = '0') + HH_4(state = '1') >> SMO_3(state = '1') + hh_mRNA_4(state = '0') + hh_mRNA_2(state = '0') + ptc_mRNA_3(state = '0') + PTC_3(state = '1') + HH_2(state = '0') + HH_4(state = '1'), on)
Rule('SMO_36', SMO_3(state = '1') + hh_mRNA_4(state = '0') + hh_mRNA_2(state = '0') + ptc_mRNA_3(state = '0') + PTC_3(state = '1') + HH_2(state = '0') + HH_4(state = '0') >> SMO_3(state = '0') + hh_mRNA_4(state = '0') + hh_mRNA_2(state = '0') + ptc_mRNA_3(state = '0') + PTC_3(state = '1') + HH_2(state = '0') + HH_4(state = '0'), on)
Rule('SMO_37', SMO_3(state = '0') + hh_mRNA_4(state = '0') + hh_mRNA_2(state = '0') + ptc_mRNA_3(state = '0') + PTC_3(state = '0') >> SMO_3(state = '1') + hh_mRNA_4(state = '0') + hh_mRNA_2(state = '0') + ptc_mRNA_3(state = '0') + PTC_3(state = '0'), on)

Rule('CIR_31', CIR_3(state = '1') + hh_mRNA_2(state = '1') >> CIR_3(state = '0') + hh_mRNA_2(state = '1'), on)
Rule('CIR_32', CIR_3(state = '1') + hh_mRNA_2(state = '0') + SMO_3(state = '1') >> CIR_3(state = '0') + hh_mRNA_2(state = '0') + SMO_3(state = '1'), on)
Rule('CIR_33', CIR_3(state = '1') + hh_mRNA_2(state = '0') + SMO_3(state = '0') + CI_3(state = '1') + hh_mRNA_4(state = '1') >> CIR_3(state = '0') + hh_mRNA_2(state = '0') + SMO_3(state = '0') + CI_3(state = '1') + hh_mRNA_4(state = '1'), on)
Rule('CIR_34', CIR_3(state = '0') + hh_mRNA_2(state = '0') + SMO_3(state = '0') + CI_3(state = '1') + hh_mRNA_4(state = '0') >> CIR_3(state = '1') + hh_mRNA_2(state = '0') + SMO_3(state = '0') + CI_3(state = '1') + hh_mRNA_4(state = '0'), on)
Rule('CIR_35', CIR_3(state = '1') + hh_mRNA_2(state = '0') + SMO_3(state = '0') + CI_3(state = '0') >> CIR_3(state = '0') + hh_mRNA_2(state = '0') + SMO_3(state = '0') + CI_3(state = '0'), on)

Rule('en_mRNA_31', en_mRNA_3(state = '1') + SLP_3(state = '1') >> en_mRNA_3(state = '0') + SLP_3(state = '1'), on)
Rule('en_mRNA_32', en_mRNA_3(state = '0') + SLP_3(state = '0') + WG_2(state = '1') >> en_mRNA_3(state = '1') + SLP_3(state = '0') + WG_2(state = '1'), on)
Rule('en_mRNA_33', en_mRNA_3(state = '0') + SLP_3(state = '0') + WG_2(state = '0') + WG_4(state = '1') >> en_mRNA_3(state = '1') + SLP_3(state = '0') + WG_2(state = '0') + WG_4(state = '1'), on)
Rule('en_mRNA_34', en_mRNA_3(state = '1') + SLP_3(state = '0') + WG_2(state = '0') + WG_4(state = '0') >> en_mRNA_3(state = '0') + SLP_3(state = '0') + WG_2(state = '0') + WG_4(state = '0'), on)

Rule('EN_11', EN_1(state = '0') + en_mRNA_1(state = '1') >> EN_1(state = '1') + en_mRNA_1(state = '1'), on)
Rule('EN_12', EN_1(state = '1') + en_mRNA_1(state = '0') >> EN_1(state = '0') + en_mRNA_1(state = '0'), on)

Rule('EN_21', EN_2(state = '0') + en_mRNA_2(state = '1') >> EN_2(state = '1') + en_mRNA_2(state = '1'), on)
Rule('EN_22', EN_2(state = '1') + en_mRNA_2(state = '0') >> EN_2(state = '0') + en_mRNA_2(state = '0'), on)

Rule('EN_31', EN_3(state = '0') + en_mRNA_3(state = '1') >> EN_3(state = '1') + en_mRNA_3(state = '1'), on)
Rule('EN_32', EN_3(state = '1') + en_mRNA_3(state = '0') >> EN_3(state = '0') + en_mRNA_3(state = '0'), on)

Rule('EN_41', EN_4(state = '0') + en_mRNA_4(state = '1') >> EN_4(state = '1') + en_mRNA_4(state = '1'), on)
Rule('EN_42', EN_4(state = '1') + en_mRNA_4(state = '0') >> EN_4(state = '0') + en_mRNA_4(state = '0'), on)

Rule('hh_mRNA_41', hh_mRNA_4(state = '1') + EN_4(state = '1') + CIR_4(state = '1') >> hh_mRNA_4(state = '0') + EN_4(state = '1') + CIR_4(state = '1'), on)
Rule('hh_mRNA_42', hh_mRNA_4(state = '0') + EN_4(state = '1') + CIR_4(state = '0') >> hh_mRNA_4(state = '1') + EN_4(state = '1') + CIR_4(state = '0'), on)
Rule('hh_mRNA_43', hh_mRNA_4(state = '1') + EN_4(state = '0') >> hh_mRNA_4(state = '0') + EN_4(state = '0'), on)

Rule('CI_11', CI_1(state = '0') + ci_mRNA_1(state = '1') >> CI_1(state = '1') + ci_mRNA_1(state = '1'), on)
Rule('CI_12', CI_1(state = '1') + ci_mRNA_1(state = '0') >> CI_1(state = '0') + ci_mRNA_1(state = '0'), on)

Rule('CI_31', CI_3(state = '0') + ci_mRNA_3(state = '1') >> CI_3(state = '1') + ci_mRNA_3(state = '1'), on)
Rule('CI_32', CI_3(state = '1') + ci_mRNA_3(state = '0') >> CI_3(state = '0') + ci_mRNA_3(state = '0'), on)

Rule('ci_mRNA_21', ci_mRNA_2(state = '1') + EN_2(state = '1') >> ci_mRNA_2(state = '0') + EN_2(state = '1'), on)
Rule('ci_mRNA_22', ci_mRNA_2(state = '0') + EN_2(state = '0') >> ci_mRNA_2(state = '1') + EN_2(state = '0'), on)

Rule('CI_41', CI_4(state = '0') + ci_mRNA_4(state = '1') >> CI_4(state = '1') + ci_mRNA_4(state = '1'), on)
Rule('CI_42', CI_4(state = '1') + ci_mRNA_4(state = '0') >> CI_4(state = '0') + ci_mRNA_4(state = '0'), on)

Rule('HH_11', HH_1(state = '0') + hh_mRNA_1(state = '1') >> HH_1(state = '1') + hh_mRNA_1(state = '1'), on)
Rule('HH_12', HH_1(state = '1') + hh_mRNA_1(state = '0') >> HH_1(state = '0') + hh_mRNA_1(state = '0'), on)

Rule('HH_31', HH_3(state = '0') + hh_mRNA_3(state = '1') >> HH_3(state = '1') + hh_mRNA_3(state = '1'), on)
Rule('HH_32', HH_3(state = '1') + hh_mRNA_3(state = '0') >> HH_3(state = '0') + hh_mRNA_3(state = '0'), on)

Rule('HH_21', HH_2(state = '0') + hh_mRNA_2(state = '1') >> HH_2(state = '1') + hh_mRNA_2(state = '1'), on)
Rule('HH_22', HH_2(state = '1') + hh_mRNA_2(state = '0') >> HH_2(state = '0') + hh_mRNA_2(state = '0'), on)

Rule('HH_41', HH_4(state = '0') + hh_mRNA_4(state = '1') >> HH_4(state = '1') + hh_mRNA_4(state = '1'), on)
Rule('HH_42', HH_4(state = '1') + hh_mRNA_4(state = '0') >> HH_4(state = '0') + hh_mRNA_4(state = '0'), on)


Rule('en_mRNA_41', en_mRNA_4(state = '1') + SLP_4(state = '1') >> en_mRNA_4(state = '0') + SLP_4(state = '1'), on)
Rule('en_mRNA_42', en_mRNA_4(state = '0') + SLP_4(state = '0') + WG_1(state = '1') >> en_mRNA_4(state = '1') + SLP_4(state = '0') + WG_1(state = '1'), on)
Rule('en_mRNA_43', en_mRNA_4(state = '0') + SLP_4(state = '0') + WG_1(state = '0') + WG_3(state = '1') >> en_mRNA_4(state = '1') + SLP_4(state = '0') + WG_1(state = '0') + WG_3(state = '1'), on)
Rule('en_mRNA_44', en_mRNA_4(state = '1') + SLP_4(state = '0') + WG_1(state = '0') + WG_3(state = '0') >> en_mRNA_4(state = '0') + SLP_4(state = '0') + WG_1(state = '0') + WG_3(state = '0'), on)

Rule('SMO_41', SMO_4(state = '0') + hh_mRNA_1(state = '1') >> SMO_4(state = '1') + hh_mRNA_1(state = '1'), on)
Rule('SMO_42', SMO_4(state = '0') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '1') >> SMO_4(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '1'), on)
Rule('SMO_43', SMO_4(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') + ptc_mRNA_4(state = '1') >> SMO_4(state = '0') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') + ptc_mRNA_4(state = '1'), on)
Rule('SMO_44', SMO_4(state = '0') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') + ptc_mRNA_4(state = '0') + HH_3(state = '1') >> SMO_4(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') + ptc_mRNA_4(state = '0') + HH_3(state = '1'), on)
Rule('SMO_45', SMO_4(state = '0') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') + ptc_mRNA_4(state = '0') + HH_3(state = '0') + HH_1(state = '1') >> SMO_4(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') + ptc_mRNA_4(state = '0') + HH_3(state = '0') + HH_1(state = '1'), on)
Rule('SMO_46', SMO_4(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') + ptc_mRNA_4(state = '0') + HH_3(state = '0') + HH_1(state = '0') + PTC_4(state = '1') >> SMO_4(state = '0') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') + ptc_mRNA_4(state = '0') + HH_3(state = '0') + HH_1(state = '0') + PTC_4(state = '1'), on)
Rule('SMO_47', SMO_4(state = '0') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') + ptc_mRNA_4(state = '0') + HH_3(state = '0') + HH_1(state = '0') + PTC_4(state = '0') >> SMO_4(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') + ptc_mRNA_4(state = '0') + HH_3(state = '0') + HH_1(state = '0') + PTC_4(state = '0'), on)

Rule('en_mRNA_21', en_mRNA_2(state = '1') + SLP_2(state = '1') >> en_mRNA_2(state = '0') + SLP_2(state = '1'), on)
Rule('en_mRNA_22', en_mRNA_2(state = '0') + SLP_2(state = '0') + WG_1(state = '1') >> en_mRNA_2(state = '1') + SLP_2(state = '0') + WG_1(state = '1'), on)
Rule('en_mRNA_23', en_mRNA_2(state = '0') + SLP_2(state = '0') + WG_1(state = '0') + WG_3(state = '1') >> en_mRNA_2(state = '1') + SLP_2(state = '0') + WG_1(state = '0') + WG_3(state = '1'), on)
Rule('en_mRNA_24', en_mRNA_2(state = '1') + SLP_2(state = '0') + WG_1(state = '0') + WG_3(state = '0') >> en_mRNA_2(state = '0') + SLP_2(state = '0') + WG_1(state = '0') + WG_3(state = '0'), on)

Rule('SMO_21', SMO_2(state = '0') + hh_mRNA_3(state = '1') >> SMO_2(state = '1') + hh_mRNA_3(state = '1'), on)
Rule('SMO_22', SMO_2(state = '0') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '1') >> SMO_2(state = '1') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '1'), on)
Rule('SMO_23', SMO_2(state = '1') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '0') + ptc_mRNA_2(state = '1') >> SMO_2(state = '0') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '0') + ptc_mRNA_2(state = '1'), on)
Rule('SMO_24', SMO_2(state = '0') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '0') + ptc_mRNA_2(state = '0') + PTC_2(state = '1') + HH_1(state = '1') >> SMO_2(state = '1') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '0') + ptc_mRNA_2(state = '0') + PTC_2(state = '1') + HH_1(state = '1'), on)
Rule('SMO_25', SMO_2(state = '0') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '0') + ptc_mRNA_2(state = '0') + PTC_2(state = '1') + HH_1(state = '0') + HH_3(state = '1') >> SMO_2(state = '1') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '0') + ptc_mRNA_2(state = '0') + PTC_2(state = '1') + HH_1(state = '0') + HH_3(state = '1'), on)
Rule('SMO_26', SMO_2(state = '1') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '0') + ptc_mRNA_2(state = '0') + PTC_2(state = '1') + HH_1(state = '0') + HH_3(state = '0') >> SMO_2(state = '0') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '0') + ptc_mRNA_2(state = '0') + PTC_2(state = '1') + HH_1(state = '0') + HH_3(state = '0'), on)
Rule('SMO_27', SMO_2(state = '0') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '0') + ptc_mRNA_2(state = '0') + PTC_2(state = '0') >> SMO_2(state = '1') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '0') + ptc_mRNA_2(state = '0') + PTC_2(state = '0'), on)

Rule('SMO_11', SMO_1(state = '0') + hh_mRNA_2(state = '1') >> SMO_1(state = '1') + hh_mRNA_2(state = '1'), on)
Rule('SMO_12', SMO_1(state = '0') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '1') >> SMO_1(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '1'), on)
Rule('SMO_13', SMO_1(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0') + ptc_mRNA_1(state = '1') >> SMO_1(state = '0') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0') + ptc_mRNA_1(state = '1'), on)
Rule('SMO_14', SMO_1(state = '0') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0') + ptc_mRNA_1(state = '0') + HH_2(state = '1') >> SMO_1(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0') + ptc_mRNA_1(state = '0') + HH_2(state = '1'), on)
Rule('SMO_15', SMO_1(state = '0') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0') + ptc_mRNA_1(state = '0') + HH_2(state = '0') + PTC_1(state = '1') + HH_4(state = '1') >> SMO_1(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0') + ptc_mRNA_1(state = '0') + HH_2(state = '0') + PTC_1(state = '1') + HH_4(state = '1'), on)
Rule('SMO_16', SMO_1(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0') + ptc_mRNA_1(state = '0') + HH_2(state = '0') + PTC_1(state = '1') + HH_4(state = '0') >> SMO_1(state = '0') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0') + ptc_mRNA_1(state = '0') + HH_2(state = '0') + PTC_1(state = '1') + HH_4(state = '0'), on)
Rule('SMO_17', SMO_1(state = '0') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0') + ptc_mRNA_1(state = '0') + HH_2(state = '0') + PTC_1(state = '0') >> SMO_1(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0') + ptc_mRNA_1(state = '0') + HH_2(state = '0') + PTC_1(state = '0'), on)

Rule('en_mRNA_11', en_mRNA_1(state = '1') + SLP_1(state = '1') >> en_mRNA_1(state = '0') + SLP_1(state = '1'), on)
Rule('en_mRNA_12', en_mRNA_1(state = '0') + SLP_1(state = '0') + WG_2(state = '1') >> en_mRNA_1(state = '1') + SLP_1(state = '0') + WG_2(state = '1'), on)
Rule('en_mRNA_13', en_mRNA_1(state = '0') + SLP_1(state = '0') + WG_2(state = '0') + WG_4(state = '1') >> en_mRNA_1(state = '1') + SLP_1(state = '0') + WG_2(state = '0') + WG_4(state = '1'), on)
Rule('en_mRNA_14', en_mRNA_1(state = '1') + SLP_1(state = '0') + WG_2(state = '0') + WG_4(state = '0') >> en_mRNA_1(state = '0') + SLP_1(state = '0') + WG_2(state = '0') + WG_4(state = '0'), on)

Rule('CIR_41', CIR_4(state = '1') + hh_mRNA_1(state = '1') >> CIR_4(state = '0') + hh_mRNA_1(state = '1'), on)
Rule('CIR_42', CIR_4(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '1') >> CIR_4(state = '0') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '1'), on)
Rule('CIR_43', CIR_4(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') + SMO_4(state = '1') >> CIR_4(state = '0') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') + SMO_4(state = '1'), on)
Rule('CIR_44', CIR_4(state = '0') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') + SMO_4(state = '0') + CI_4(state = '1') >> CIR_4(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') + SMO_4(state = '0') + CI_4(state = '1'), on)
Rule('CIR_45', CIR_4(state = '1') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') + SMO_4(state = '0') + CI_4(state = '0') >> CIR_4(state = '0') + hh_mRNA_1(state = '0') + hh_mRNA_3(state = '0') + SMO_4(state = '0') + CI_4(state = '0'), on)

Rule('ptc_mRNA_41', ptc_mRNA_4(state = '1') + EN_4(state = '1') >> ptc_mRNA_4(state = '0') + EN_4(state = '1'), on)
Rule('ptc_mRNA_42', ptc_mRNA_4(state = '1') + EN_4(state = '0') + CIA_4(state = '1') + CIR_4(state = '1') >> ptc_mRNA_4(state = '0') + EN_4(state = '0') + CIA_4(state = '1') + CIR_4(state = '1'), on)
Rule('ptc_mRNA_43', ptc_mRNA_4(state = '0') + EN_4(state = '0') + CIA_4(state = '1') + CIR_4(state = '0') >> ptc_mRNA_4(state = '1') + EN_4(state = '0') + CIA_4(state = '1') + CIR_4(state = '0'), on)
Rule('ptc_mRNA_44', ptc_mRNA_4(state = '1') + EN_4(state = '0') + CIA_4(state = '0') >> ptc_mRNA_4(state = '0') + EN_4(state = '0') + CIA_4(state = '0'), on)

Rule('CIR_21', CIR_2(state = '1') + hh_mRNA_1(state = '1') >> CIR_2(state = '0') + hh_mRNA_1(state = '1'), on)
Rule('CIR_22', CIR_2(state = '1') + hh_mRNA_1(state = '0') + SMO_2(state = '1') >> CIR_2(state = '0') + hh_mRNA_1(state = '0') + SMO_2(state = '1'), on)
Rule('CIR_23', CIR_2(state = '1') + hh_mRNA_1(state = '0') + SMO_2(state = '0') + CI_2(state = '1') + hh_mRNA_3(state = '1') >> CIR_2(state = '0') + hh_mRNA_1(state = '0') + SMO_2(state = '0') + CI_2(state = '1') + hh_mRNA_3(state = '1'), on)
Rule('CIR_24', CIR_2(state = '0') + hh_mRNA_1(state = '0') + SMO_2(state = '0') + CI_2(state = '1') + hh_mRNA_3(state = '0') >> CIR_2(state = '1') + hh_mRNA_1(state = '0') + SMO_2(state = '0') + CI_2(state = '1') + hh_mRNA_3(state = '0'), on)
Rule('CIR_25', CIR_2(state = '1') + hh_mRNA_1(state = '0') + SMO_2(state = '0') + CI_2(state = '0') >> CIR_2(state = '0') + hh_mRNA_1(state = '0') + SMO_2(state = '0') + CI_2(state = '0'), on)

Rule('CIA_31', CIA_3(state = '0') + CI_3(state = '1') + hh_mRNA_2(state = '1') >> CIA_3(state = '1') + CI_3(state = '1') + hh_mRNA_2(state = '1'), on)
Rule('CIA_32', CIA_3(state = '0') + CI_3(state = '1') + hh_mRNA_2(state = '0') + SMO_3(state = '1') >> CIA_3(state = '1') + CI_3(state = '1') + hh_mRNA_2(state = '0') + SMO_3(state = '1'), on)
Rule('CIA_33', CIA_3(state = '0') + CI_3(state = '1') + hh_mRNA_2(state = '0') + SMO_3(state = '0') + hh_mRNA_4(state = '1') >> CIA_3(state = '1') + CI_3(state = '1') + hh_mRNA_2(state = '0') + SMO_3(state = '0') + hh_mRNA_4(state = '1'), on)
Rule('CIA_34', CIA_3(state = '1') + CI_3(state = '1') + hh_mRNA_2(state = '0') + SMO_3(state = '0') + hh_mRNA_4(state = '0') >> CIA_3(state = '0') + CI_3(state = '1') + hh_mRNA_2(state = '0') + SMO_3(state = '0') + hh_mRNA_4(state = '0'), on)
Rule('CIA_35', CIA_3(state = '1') + CI_3(state = '0') >> CIA_3(state = '0') + CI_3(state = '0'), on)

Rule('ci_mRNA_41', ci_mRNA_4(state = '1') + EN_4(state = '1') >> ci_mRNA_4(state = '0') + EN_4(state = '1'), on)
Rule('ci_mRNA_42', ci_mRNA_4(state = '0') + EN_4(state = '0') >> ci_mRNA_4(state = '1') + EN_4(state = '0'), on)

Rule('CIR_11', CIR_1(state = '1') + SMO_1(state = '1') >> CIR_1(state = '0') + SMO_1(state = '1'), on)
Rule('CIR_12', CIR_1(state = '1') + SMO_1(state = '0') + CI_1(state = '1') + hh_mRNA_2(state = '1') >> CIR_1(state = '0') + SMO_1(state = '0') + CI_1(state = '1') + hh_mRNA_2(state = '1'), on)
Rule('CIR_13', CIR_1(state = '1') + SMO_1(state = '0') + CI_1(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '1') >> CIR_1(state = '0') + SMO_1(state = '0') + CI_1(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '1'), on)
Rule('CIR_14', CIR_1(state = '0') + SMO_1(state = '0') + CI_1(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0') >> CIR_1(state = '1') + SMO_1(state = '0') + CI_1(state = '1') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0'), on)
Rule('CIR_15', CIR_1(state = '1') + SMO_1(state = '0') + CI_1(state = '0') >> CIR_1(state = '0') + SMO_1(state = '0') + CI_1(state = '0'), on)

Rule('wg_mRNA_41', wg_mRNA_4(state = '1') + CIR_4(state = '1') >> wg_mRNA_4(state = '0') + CIR_4(state = '1'), on)
Rule('wg_mRNA_44', CIR_4(state = '0') + wg_mRNA_4(state = '1') + SLP_4(state = '0') + CIA_4(state = '0') >> CIR_4(state = '0') + wg_mRNA_4(state = '0') + SLP_4(state = '0') + CIA_4(state = '0'), on)
Rule('wg_mRNA_45', CIR_4(state = '0') + wg_mRNA_4(state = '0') + SLP_4(state = '1') + CIA_4(state = '1') >> CIR_4(state = '0') + wg_mRNA_4(state = '1') + SLP_4(state = '1') + CIA_4(state = '1'), on)

Rule('CIA_11', CIA_1(state = '0') + CI_1(state = '1') + SMO_1(state = '1') >> CIA_1(state = '1') + CI_1(state = '1') + SMO_1(state = '1'), on)
Rule('CIA_12', CIA_1(state = '0') + CI_1(state = '1') + SMO_1(state = '0') + hh_mRNA_2(state = '1') >> CIA_1(state = '1') + CI_1(state = '1') + SMO_1(state = '0') + hh_mRNA_2(state = '1'), on)
Rule('CIA_13', CIA_1(state = '0') + CI_1(state = '1') + SMO_1(state = '0') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '1') >> CIA_1(state = '1') + CI_1(state = '1') + SMO_1(state = '0') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '1'), on)
Rule('CIA_14', CIA_1(state = '1') + CI_1(state = '1') + SMO_1(state = '0') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0') >> CIA_1(state = '0') + CI_1(state = '1') + SMO_1(state = '0') + hh_mRNA_2(state = '0') + hh_mRNA_4(state = '0'), on)
Rule('CIA_15', CIA_1(state = '1') + CI_1(state = '0') >> CIA_1(state = '0') + CI_1(state = '0'), on)



Rule('CIA_21', CIA_2(state = '0') + CI_2(state = '1') + hh_mRNA_1(state = '1') >> CIA_2(state = '1') + CI_2(state = '1') + hh_mRNA_1(state = '1'), on)
Rule('CIA_22', CIA_2(state = '0') + CI_2(state = '1') + hh_mRNA_1(state = '0') + SMO_2(state = '1') >> CIA_2(state = '1') + CI_2(state = '1') + hh_mRNA_1(state = '0') + SMO_2(state = '1'), on)
Rule('CIA_23', CIA_2(state = '0') + CI_2(state = '1') + hh_mRNA_1(state = '0') + SMO_2(state = '0') + hh_mRNA_3(state = '1') >> CIA_2(state = '1') + CI_2(state = '1') + hh_mRNA_1(state = '0') + SMO_2(state = '0') + hh_mRNA_3(state = '1'), on)
Rule('CIA_24', CIA_2(state = '1') + CI_2(state = '1') + hh_mRNA_1(state = '0') + SMO_2(state = '0') + hh_mRNA_3(state = '0') >> CIA_2(state = '0') + CI_2(state = '1') + hh_mRNA_1(state = '0') + SMO_2(state = '0') + hh_mRNA_3(state = '0'), on)
Rule('CIA_25', CIA_2(state = '1') + CI_2(state = '0') >> CIA_2(state = '0') + CI_2(state = '0'), on)

Rule('CIA_41', CIA_4(state = '0') + CI_4(state = '1') + hh_mRNA_3(state = '1') >> CIA_4(state = '1') + CI_4(state = '1') + hh_mRNA_3(state = '1'), on)
Rule('CIA_42', CIA_4(state = '0') + CI_4(state = '1') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '1') >> CIA_4(state = '1') + CI_4(state = '1') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '1'), on)
Rule('CIA_43', CIA_4(state = '0') + CI_4(state = '1') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '0') + SMO_4(state = '1') >> CIA_4(state = '1') + CI_4(state = '1') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '0') + SMO_4(state = '1'), on)
Rule('CIA_44', CIA_4(state = '1') + CI_4(state = '1') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '0') + SMO_4(state = '0') >> CIA_4(state = '0') + CI_4(state = '1') + hh_mRNA_3(state = '0') + hh_mRNA_1(state = '0') + SMO_4(state = '0'), on)
Rule('CIA_45', CIA_4(state = '1') + CI_4(state = '0') >> CIA_4(state = '0') + CI_4(state = '0'), on)


Rule('ptc_mRNA_31', ptc_mRNA_3(state = '1') + EN_3(state = '1') >> ptc_mRNA_3(state = '0') + EN_3(state = '1'), on)
Rule('ptc_mRNA_32', ptc_mRNA_3(state = '1') + EN_3(state = '0') + CIA_3(state = '1') + CIR_3(state = '1') >> ptc_mRNA_3(state = '0') + EN_3(state = '0') + CIA_3(state = '1') + CIR_3(state = '1'), on)
Rule('ptc_mRNA_33', ptc_mRNA_3(state = '0') + EN_3(state = '0') + CIA_3(state = '1') + CIR_3(state = '0') >> ptc_mRNA_3(state = '1') + EN_3(state = '0') + CIA_3(state = '1') + CIR_3(state = '0'), on)
Rule('ptc_mRNA_34', ptc_mRNA_3(state = '1') + EN_3(state = '0') + CIA_3(state = '0') >> ptc_mRNA_3(state = '0') + EN_3(state = '0') + CIA_3(state = '0'), on)

Rule('ptc_mRNA_21', ptc_mRNA_2(state = '1') + EN_2(state = '1') >> ptc_mRNA_2(state = '0') + EN_2(state = '1'), on)
Rule('ptc_mRNA_22', ptc_mRNA_2(state = '1') + EN_2(state = '0') + CIA_2(state = '1') + CIR_2(state = '1') >> ptc_mRNA_2(state = '0') + EN_2(state = '0') + CIA_2(state = '1') + CIR_2(state = '1'), on)
Rule('ptc_mRNA_23', ptc_mRNA_2(state = '0') + EN_2(state = '0') + CIA_2(state = '1') + CIR_2(state = '0') >> ptc_mRNA_2(state = '1') + EN_2(state = '0') + CIA_2(state = '1') + CIR_2(state = '0'), on)
Rule('ptc_mRNA_24', ptc_mRNA_2(state = '1') + EN_2(state = '0') + CIA_2(state = '0') >> ptc_mRNA_2(state = '0') + EN_2(state = '0') + CIA_2(state = '0'), on)

Rule('ptc_mRNA_11', ptc_mRNA_1(state = '1') + EN_1(state = '1') >> ptc_mRNA_1(state = '0') + EN_1(state = '1'), on)
Rule('ptc_mRNA_12', ptc_mRNA_1(state = '1') + EN_1(state = '0') + CIA_1(state = '1') + CIR_1(state = '1') >> ptc_mRNA_1(state = '0') + EN_1(state = '0') + CIA_1(state = '1') + CIR_1(state = '1'), on)
Rule('ptc_mRNA_13', ptc_mRNA_1(state = '0') + EN_1(state = '0') + CIA_1(state = '1') + CIR_1(state = '0') >> ptc_mRNA_1(state = '1') + EN_1(state = '0') + CIA_1(state = '1') + CIR_1(state = '0'), on)
Rule('ptc_mRNA_14', ptc_mRNA_1(state = '1') + EN_1(state = '0') + CIA_1(state = '0') >> ptc_mRNA_1(state = '0') + EN_1(state = '0') + CIA_1(state = '0'), on)

Rule('hh_mRNA_11', hh_mRNA_1(state = '1') + EN_1(state = '1') + CIR_1(state = '1') >> hh_mRNA_1(state = '0') + EN_1(state = '1') + CIR_1(state = '1'), on)
Rule('hh_mRNA_12', hh_mRNA_1(state = '0') + EN_1(state = '1') + CIR_1(state = '0') >> hh_mRNA_1(state = '1') + EN_1(state = '1') + CIR_1(state = '0'), on)
Rule('hh_mRNA_13', hh_mRNA_1(state = '1') + EN_1(state = '0') >> hh_mRNA_1(state = '0') + EN_1(state = '0'), on)

Rule('hh_mRNA_31', hh_mRNA_3(state = '1') + EN_3(state = '1') + CIR_3(state = '1') >> hh_mRNA_3(state = '0') + EN_3(state = '1') + CIR_3(state = '1'), on)
Rule('hh_mRNA_32', hh_mRNA_3(state = '0') + EN_3(state = '1') + CIR_3(state = '0') >> hh_mRNA_3(state = '1') + EN_3(state = '1') + CIR_3(state = '0'), on)
Rule('hh_mRNA_33', hh_mRNA_3(state = '1') + EN_3(state = '0') >> hh_mRNA_3(state = '0') + EN_3(state = '0'), on)

Rule('hh_mRNA_21', hh_mRNA_2(state = '1') + EN_2(state = '1') + CIR_2(state = '1') >> hh_mRNA_2(state = '0') + EN_2(state = '1') + CIR_2(state = '1'), on)
Rule('hh_mRNA_22', hh_mRNA_2(state = '0') + EN_2(state = '1') + CIR_2(state = '0') >> hh_mRNA_2(state = '1') + EN_2(state = '1') + CIR_2(state = '0'), on)
Rule('hh_mRNA_23', hh_mRNA_2(state = '1') + EN_2(state = '0') >> hh_mRNA_2(state = '0') + EN_2(state = '0'), on)

Rule('PTC_41', PTC_4(state = '0') + ptc_mRNA_4(state = '1') >> PTC_4(state = '1') + ptc_mRNA_4(state = '1'), on)
Rule('PTC_42', PTC_4(state = '1') + ptc_mRNA_4(state = '0') + HH_1(state = '1') >> PTC_4(state = '0') + ptc_mRNA_4(state = '0') + HH_1(state = '1'), on)
Rule('PTC_43', PTC_4(state = '1') + ptc_mRNA_4(state = '0') + HH_1(state = '0') + HH_3(state = '1') >> PTC_4(state = '0') + ptc_mRNA_4(state = '0') + HH_1(state = '0') + HH_3(state = '1'), on)

Rule('WG_41', WG_4(state = '0') + wg_mRNA_4(state = '1') >> WG_4(state = '1') + wg_mRNA_4(state = '1'), on)
Rule('WG_42', WG_4(state = '1') + wg_mRNA_4(state = '0') >> WG_4(state = '0') + wg_mRNA_4(state = '0'), on)

Rule('WG_31', WG_3(state = '0') + wg_mRNA_3(state = '1') >> WG_3(state = '1') + wg_mRNA_3(state = '1'), on)
Rule('WG_32', WG_3(state = '1') + wg_mRNA_3(state = '0') >> WG_3(state = '0') + wg_mRNA_3(state = '0'), on)

Rule('WG_21', WG_2(state = '0') + wg_mRNA_2(state = '1') >> WG_2(state = '1') + wg_mRNA_2(state = '1'), on)
Rule('WG_22', WG_2(state = '1') + wg_mRNA_2(state = '0') >> WG_2(state = '0') + wg_mRNA_2(state = '0'), on)

Rule('WG_11', WG_1(state = '0') + wg_mRNA_1(state = '1') >> WG_1(state = '1') + wg_mRNA_1(state = '1'), on)
Rule('WG_12', WG_1(state = '1') + wg_mRNA_1(state = '0') >> WG_1(state = '0') + wg_mRNA_1(state = '0'), on)

