from pysb import *
from sympy import sympify

Model()

# This model of the segment polarity network consists of 4 cells and 6 faces per cell

# Monomers
Monomer('en_1') # engrailed mRNA cell 1
Monomer('en_2') # "            " cell 2
Monomer('en_3')
Monomer('en_4')
Monomer('EN_1') # engrailed protein
Monomer('EN_2')
Monomer('EN_3')
Monomer('EN_4')
Monomer('wg_1') # wingless mRNA
Monomer('wg_2')
Monomer('wg_3')
Monomer('wg_4')
Monomer('IWG_1') # intracellular wingless protein
Monomer('IWG_2')
Monomer('IWG_3')
Monomer('IWG_4')
Monomer('EWG_1_1') # extracellular wingless protein cell 1 face 1
Monomer('EWG_1_2') # "                                   " face 2
Monomer('EWG_1_3')
Monomer('EWG_1_4')
Monomer('EWG_1_5')
Monomer('EWG_1_6')
Monomer('EWG_2_1')
Monomer('EWG_2_2')
Monomer('EWG_2_3')
Monomer('EWG_2_4')
Monomer('EWG_2_5')
Monomer('EWG_2_6')
Monomer('EWG_3_1')
Monomer('EWG_3_2')
Monomer('EWG_3_3')
Monomer('EWG_3_4')
Monomer('EWG_3_5')
Monomer('EWG_3_6')
Monomer('EWG_4_1')
Monomer('EWG_4_2')
Monomer('EWG_4_3')
Monomer('EWG_4_4')
Monomer('EWG_4_5')
Monomer('EWG_4_6')
Monomer('ptc_1') # patched mRNA
Monomer('ptc_2')
Monomer('ptc_3')
Monomer('ptc_4')
Monomer('PTC_1_1') # patched protein
Monomer('PTC_1_2')
Monomer('PTC_1_3')
Monomer('PTC_1_4')
Monomer('PTC_1_5')
Monomer('PTC_1_6')
Monomer('PTC_2_1')
Monomer('PTC_2_2')
Monomer('PTC_2_3')
Monomer('PTC_2_4')
Monomer('PTC_2_5')
Monomer('PTC_2_6')
Monomer('PTC_3_1')
Monomer('PTC_3_2')
Monomer('PTC_3_3')
Monomer('PTC_3_4')
Monomer('PTC_3_5')
Monomer('PTC_3_6')
Monomer('PTC_4_1')
Monomer('PTC_4_2')
Monomer('PTC_4_3')
Monomer('PTC_4_4')
Monomer('PTC_4_5')
Monomer('PTC_4_6')
Monomer('ci_1') # cubitus interuptus mRNA
Monomer('ci_2')
Monomer('ci_3')
Monomer('ci_4')
Monomer('CI_1') # full length cubitus interuptus protein
Monomer('CI_2')
Monomer('CI_3')
Monomer('CI_4')
Monomer('CN_1') # cleaved cubitus interuptus protein
Monomer('CN_2')
Monomer('CN_3')
Monomer('CN_4')
Monomer('hh_1') # hedgehog mRNA
Monomer('hh_2')
Monomer('hh_3')
Monomer('hh_4')
Monomer('HH_1_1') # hedgehog protein
Monomer('HH_1_2')
Monomer('HH_1_3')
Monomer('HH_1_4')
Monomer('HH_1_5')
Monomer('HH_1_6')
Monomer('HH_2_1')
Monomer('HH_2_2')
Monomer('HH_2_3')
Monomer('HH_2_4')
Monomer('HH_2_5')
Monomer('HH_2_6')
Monomer('HH_3_1')
Monomer('HH_3_2')
Monomer('HH_3_3')
Monomer('HH_3_4')
Monomer('HH_3_5')
Monomer('HH_3_6')
Monomer('HH_4_1')
Monomer('HH_4_2')
Monomer('HH_4_3')
Monomer('HH_4_4')
Monomer('HH_4_5')
Monomer('HH_4_6')
Monomer('PH_1_1') # patched-hedgehog protein complex
Monomer('PH_1_2')
Monomer('PH_1_3')
Monomer('PH_1_4')
Monomer('PH_1_5')
Monomer('PH_1_6')
Monomer('PH_2_1')
Monomer('PH_2_2')
Monomer('PH_2_3')
Monomer('PH_2_4')
Monomer('PH_2_5')
Monomer('PH_2_6')
Monomer('PH_3_1')
Monomer('PH_3_2')
Monomer('PH_3_3')
Monomer('PH_3_4')
Monomer('PH_3_5')
Monomer('PH_3_6')
Monomer('PH_4_1')
Monomer('PH_4_2')
Monomer('PH_4_3')
Monomer('PH_4_4')
Monomer('PH_4_5')
Monomer('PH_4_6')

# Parameters

# see Dassow (2000) supplementary information and the Ingeneue website 
# K_XXyy = XX concentration at which yy is half maximally activated
# nu_XXyy cooperativity coefficient
# H_XX = half-life of XX
# Endo_XX = rate at which XX is endocytosed
# Exo_XX = rate at which XX is exocytosed
# Mxfer_XX rate at which XX diffuses from one cell to another
# LMxfer_XX rate at which XX diffuses around the cell perimeter
# maxXX = maximal steady state concentration of XX
# k_XXYY = how avidly XX stimulates cleavage of YY
# C_XX = maximum cleavage rate (CI -> CN)

Parameter('K_WGen', 0.016870342)
Parameter('nu_WGen', 8.195488)
Parameter('H_en', 1.0/56.195484)
Parameter('K_CNen', 0.0015239986) #0.001523986
Parameter('nu_CNen', 5.929026)
Parameter('H_EN', 1.0/26.655169)
Parameter('H_wg', 1.0/65.74263)
Parameter('K_WGwg', 0.010839762)
Parameter('nu_WGwg', 5.2690034)
Parameter('alpha_WGwg', 1.2893039)
Parameter('K_CIwg', 0.1358894)
Parameter('nu_CIwg', 3.0448556)
Parameter('alpha_CIwg', 5.354691)
Parameter('K_CNwg', 0.08410451)
Parameter('nu_CNwg', 2.2106833)
Parameter('H_IWG', 1.0/95.70869)
Parameter('Endo_WG', 0.010213904) #/6)
Parameter('Exo_WG', 0.36542872/6)
Parameter('Mxfer_WG', 0.0014474009)
Parameter('LMxfer_WG', 0.0012071289)
Parameter('H_EWG', 1.0/47.52389)
Parameter('K_CIptc', 0.0012549695)
Parameter('nu_CIptc', 3.5400295)
Parameter('H_ptc', 1.0/62.299126)
Parameter('K_CNptc', 0.15335482)
Parameter('nu_CNptc', 9.436314)
Parameter('K_PTC_HH', 0.000029159914)
Parameter('max_HH', 200459.66)
Parameter('H_PTC', 1.0/18.859844)
Parameter('H_PTC_6th', 1.0/(6*18.859844))
Parameter('LMxfer_PTC', 0.010720446)
Parameter('K_Bci', 0.016921775)
Parameter('nu_Bci', 1.0)
Parameter('H_ci', 1.0/88.05598)
Parameter('K_ENci', 0.05230557)
Parameter('nu_ENci', 3.1201758)
Parameter('K_PTCCI', 0.13505042)
Parameter('nu_PTCCI', 2.4668233)
Parameter('C_CI', 0.28579983)
Parameter('H_CI', 1.0/20.967995)
Parameter('H_CN', 1.0/17.765957)
Parameter('K_ENhh', 0.5281546)
Parameter('nu_ENhh', 6.2349424)
Parameter('H_hh', 1.0/44.147385)
Parameter('K_CNhh', 0.0031077564)
Parameter('nu_CNhh', 3.7770782)
Parameter('max_PTC', 1894.0778)
Parameter('H_HH', 1.0/28.393164)
Parameter('H_HH_6th', 1.0/(6*28.393164))
Parameter('LMxfer_HH', 0.010256403)
Parameter('H_PH', 1.0/92.6156)
Parameter("B", 0.4) # determines ci expression

# IC's'
Initial(en_1(), Parameter('en_1_0', 0))
Initial(en_2(), Parameter('en_2_0', 0))
Initial(en_3(), Parameter('en_3_0', 1.0))
Initial(en_4(), Parameter('en_4_0', 0))
Initial(EN_1(), Parameter('EN_1_0', 0))
Initial(EN_2(), Parameter('EN_2_0', 0))
Initial(EN_3(), Parameter('EN_3_0', 1.0))
Initial(EN_4(), Parameter('EN_4_0', 0))
Initial(wg_1(), Parameter('wg_1_0', 0))
Initial(wg_2(), Parameter('wg_2_0', 1.0))
Initial(wg_3(), Parameter('wg_3_0', 0))
Initial(wg_4(), Parameter('wg_4_0', 0))
Initial(IWG_1(), Parameter('IWG_1_0', 0))
Initial(IWG_2(), Parameter('IWG_2_0', 1.0))
Initial(IWG_3(), Parameter('IWG_3_0', 0))
Initial(IWG_4(), Parameter('IWG_4_0', 0))
Initial(EWG_1_1(), Parameter('EWG_1_1_0', 0))
Initial(EWG_1_2(), Parameter('EWG_1_2_0', 0))
Initial(EWG_1_3(), Parameter('EWG_1_3_0', 0))
Initial(EWG_1_4(), Parameter('EWG_1_4_0', 0))
Initial(EWG_1_5(), Parameter('EWG_1_5_0', 0))
Initial(EWG_1_6(), Parameter('EWG_1_6_0', 0))
Initial(EWG_2_1(), Parameter('EWG_2_1_0', 0))
Initial(EWG_2_2(), Parameter('EWG_2_2_0', 0))
Initial(EWG_2_3(), Parameter('EWG_2_3_0', 0))
Initial(EWG_2_4(), Parameter('EWG_2_4_0', 0))
Initial(EWG_2_5(), Parameter('EWG_2_5_0', 0))
Initial(EWG_2_6(), Parameter('EWG_2_6_0', 0))
Initial(EWG_3_1(), Parameter('EWG_3_1_0', 0))
Initial(EWG_3_2(), Parameter('EWG_3_2_0', 0))
Initial(EWG_3_3(), Parameter('EWG_3_3_0', 0))
Initial(EWG_3_4(), Parameter('EWG_3_4_0', 0))
Initial(EWG_3_5(), Parameter('EWG_3_5_0', 0))
Initial(EWG_3_6(), Parameter('EWG_3_6_0', 0))
Initial(EWG_4_1(), Parameter('EWG_4_1_0', 0))
Initial(EWG_4_2(), Parameter('EWG_4_2_0', 0))
Initial(EWG_4_3(), Parameter('EWG_4_3_0', 0))
Initial(EWG_4_4(), Parameter('EWG_4_4_0', 0))
Initial(EWG_4_5(), Parameter('EWG_4_5_0', 0))
Initial(EWG_4_6(), Parameter('EWG_4_6_0', 0))
Initial(ptc_1(), Parameter('ptc_1_0', 0))
Initial(ptc_2(), Parameter('ptc_2_0', 0))
Initial(ptc_3(), Parameter('ptc_3_0', 0))
Initial(ptc_4(), Parameter('ptc_4_0', 0))
Initial(PTC_1_1(), Parameter('PTC_1_1_0', 0))
Initial(PTC_1_2(), Parameter('PTC_1_2_0', 0))
Initial(PTC_1_3(), Parameter('PTC_1_3_0', 0))
Initial(PTC_1_4(), Parameter('PTC_1_4_0', 0))
Initial(PTC_1_5(), Parameter('PTC_1_5_0', 0))
Initial(PTC_1_6(), Parameter('PTC_1_6_0', 0))
Initial(PTC_2_1(), Parameter('PTC_2_1_0', 0))
Initial(PTC_2_2(), Parameter('PTC_2_2_0', 0))
Initial(PTC_2_3(), Parameter('PTC_2_3_0', 0))
Initial(PTC_2_4(), Parameter('PTC_2_4_0', 0))
Initial(PTC_2_5(), Parameter('PTC_2_5_0', 0))
Initial(PTC_2_6(), Parameter('PTC_2_6_0', 0))
Initial(PTC_3_1(), Parameter('PTC_3_1_0', 0))
Initial(PTC_3_2(), Parameter('PTC_3_2_0', 0))
Initial(PTC_3_3(), Parameter('PTC_3_3_0', 0))
Initial(PTC_3_4(), Parameter('PTC_3_4_0', 0))
Initial(PTC_3_5(), Parameter('PTC_3_5_0', 0))
Initial(PTC_3_6(), Parameter('PTC_3_6_0', 0))
Initial(PTC_4_1(), Parameter('PTC_4_1_0', 0))
Initial(PTC_4_2(), Parameter('PTC_4_2_0', 0))
Initial(PTC_4_3(), Parameter('PTC_4_3_0', 0))
Initial(PTC_4_4(), Parameter('PTC_4_4_0', 0))
Initial(PTC_4_5(), Parameter('PTC_4_5_0', 0))
Initial(PTC_4_6(), Parameter('PTC_4_6_0', 0))
Initial(ci_1(), Parameter('ci_1_0', 0))
Initial(ci_2(), Parameter('ci_2_0', 0))
Initial(ci_3(), Parameter('ci_3_0', 0))
Initial(ci_4(), Parameter('ci_4_0', 0))
Initial(CI_1(), Parameter('CI_1_0', 0))
Initial(CI_2(), Parameter('CI_2_0', 0)) # 0.000001
Initial(CI_3(), Parameter('CI_3_0', 0)) # 0.000001
Initial(CI_4(), Parameter('CI_4_0', 0)) # 0.000001
Initial(CN_1(), Parameter('CN_1_0', 0))
Initial(CN_2(), Parameter('CN_2_0', 0))
Initial(CN_3(), Parameter('CN_3_0', 0))
Initial(CN_4(), Parameter('CN_4_0', 0))
Initial(hh_1(), Parameter('hh_1_0', 0))
Initial(hh_2(), Parameter('hh_2_0', 0))
Initial(hh_3(), Parameter('hh_3_0', 0))
Initial(hh_4(), Parameter('hh_4_0', 0))
Initial(HH_1_1(), Parameter('HH_1_1_0', 0))
Initial(HH_1_2(), Parameter('HH_1_2_0', 0))
Initial(HH_1_3(), Parameter('HH_1_3_0', 0))
Initial(HH_1_4(), Parameter('HH_1_4_0', 0))
Initial(HH_1_5(), Parameter('HH_1_5_0', 0))
Initial(HH_1_6(), Parameter('HH_1_6_0', 0))
Initial(HH_2_1(), Parameter('HH_2_1_0', 0))
Initial(HH_2_2(), Parameter('HH_2_2_0', 0))
Initial(HH_2_3(), Parameter('HH_2_3_0', 0))
Initial(HH_2_4(), Parameter('HH_2_4_0', 0))
Initial(HH_2_5(), Parameter('HH_2_5_0', 0))
Initial(HH_2_6(), Parameter('HH_2_6_0', 0))
Initial(HH_3_1(), Parameter('HH_3_1_0', 0))
Initial(HH_3_2(), Parameter('HH_3_2_0', 0))
Initial(HH_3_3(), Parameter('HH_3_3_0', 0))
Initial(HH_3_4(), Parameter('HH_3_4_0', 0))
Initial(HH_3_5(), Parameter('HH_3_5_0', 0))
Initial(HH_3_6(), Parameter('HH_3_6_0', 0))
Initial(HH_4_1(), Parameter('HH_4_1_0', 0))
Initial(HH_4_2(), Parameter('HH_4_2_0', 0))
Initial(HH_4_3(), Parameter('HH_4_3_0', 0))
Initial(HH_4_4(), Parameter('HH_4_4_0', 0))
Initial(HH_4_5(), Parameter('HH_4_5_0', 0))
Initial(HH_4_6(), Parameter('HH_4_6_0', 0))
Initial(PH_1_1(), Parameter('PH_1_1_0', 0))
Initial(PH_1_2(), Parameter('PH_1_2_0', 0))
Initial(PH_1_3(), Parameter('PH_1_3_0', 0))
Initial(PH_1_4(), Parameter('PH_1_4_0', 0))
Initial(PH_1_5(), Parameter('PH_1_5_0', 0))
Initial(PH_1_6(), Parameter('PH_1_6_0', 0))
Initial(PH_2_1(), Parameter('PH_2_1_0', 0))
Initial(PH_2_2(), Parameter('PH_2_2_0', 0))
Initial(PH_2_3(), Parameter('PH_2_3_0', 0))
Initial(PH_2_4(), Parameter('PH_2_4_0', 0))
Initial(PH_2_5(), Parameter('PH_2_5_0', 0))
Initial(PH_2_6(), Parameter('PH_2_6_0', 0))
Initial(PH_3_1(), Parameter('PH_3_1_0', 0))
Initial(PH_3_2(), Parameter('PH_3_2_0', 0))
Initial(PH_3_3(), Parameter('PH_3_3_0', 0))
Initial(PH_3_4(), Parameter('PH_3_4_0', 0))
Initial(PH_3_5(), Parameter('PH_3_5_0', 0))
Initial(PH_3_6(), Parameter('PH_3_6_0', 0))
Initial(PH_4_1(), Parameter('PH_4_1_0', 0))
Initial(PH_4_2(), Parameter('PH_4_2_0', 0))
Initial(PH_4_3(), Parameter('PH_4_3_0', 0))
Initial(PH_4_4(), Parameter('PH_4_4_0', 0))
Initial(PH_4_5(), Parameter('PH_4_5_0', 0))
Initial(PH_4_6(), Parameter('PH_4_6_0', 0))

# Observables
Observable('en_1_obs', en_1())
Observable('en_2_obs', en_2())
Observable('en_3_obs', en_3())
Observable('en_4_obs', en_4())
Observable('EN_1_obs', EN_1())
Observable('EN_2_obs', EN_2())
Observable('EN_3_obs', EN_3())
Observable('EN_4_obs', EN_4())
Observable('wg_1_obs', wg_1())
Observable('wg_2_obs', wg_2())
Observable('wg_3_obs', wg_3())
Observable('wg_4_obs', wg_4())
Observable('IWG_1_obs', IWG_1())
Observable('IWG_2_obs', IWG_2())
Observable('IWG_3_obs', IWG_3())
Observable('IWG_4_obs', IWG_4())
Observable('EWG_1_1_obs', EWG_1_1())
Observable('EWG_1_2_obs', EWG_1_2())
Observable('EWG_1_3_obs', EWG_1_3())
Observable('EWG_1_4_obs', EWG_1_4())
Observable('EWG_1_5_obs', EWG_1_5())
Observable('EWG_1_6_obs', EWG_1_6())
Observable('EWG_2_1_obs', EWG_2_1())
Observable('EWG_2_2_obs', EWG_2_2())
Observable('EWG_2_3_obs', EWG_2_3())
Observable('EWG_2_4_obs', EWG_2_4())
Observable('EWG_2_5_obs', EWG_2_5())
Observable('EWG_2_6_obs', EWG_2_6())
Observable('EWG_3_1_obs', EWG_3_1())
Observable('EWG_3_2_obs', EWG_3_2())
Observable('EWG_3_3_obs', EWG_3_3())
Observable('EWG_3_4_obs', EWG_3_4())
Observable('EWG_3_5_obs', EWG_3_5())
Observable('EWG_3_6_obs', EWG_3_6())
Observable('EWG_4_1_obs', EWG_4_1())
Observable('EWG_4_2_obs', EWG_4_2())
Observable('EWG_4_3_obs', EWG_4_3())
Observable('EWG_4_4_obs', EWG_4_4())
Observable('EWG_4_5_obs', EWG_4_5())
Observable('EWG_4_6_obs', EWG_4_6())
Observable('ptc_1_obs', ptc_1())
Observable('ptc_2_obs', ptc_2())
Observable('ptc_3_obs', ptc_3())
Observable('ptc_4_obs', ptc_4())
Observable('PTC_1_1_obs', PTC_1_1())
Observable('PTC_1_2_obs', PTC_1_2())
Observable('PTC_1_3_obs', PTC_1_3())
Observable('PTC_1_4_obs', PTC_1_4())
Observable('PTC_1_5_obs', PTC_1_5())
Observable('PTC_1_6_obs', PTC_1_6())
Observable('PTC_2_1_obs', PTC_2_1())
Observable('PTC_2_2_obs', PTC_2_2())
Observable('PTC_2_3_obs', PTC_2_3())
Observable('PTC_2_4_obs', PTC_2_4())
Observable('PTC_2_5_obs', PTC_2_5())
Observable('PTC_2_6_obs', PTC_2_6())
Observable('PTC_3_1_obs', PTC_3_1())
Observable('PTC_3_2_obs', PTC_3_2())
Observable('PTC_3_3_obs', PTC_3_3())
Observable('PTC_3_4_obs', PTC_3_4())
Observable('PTC_3_5_obs', PTC_3_5())
Observable('PTC_3_6_obs', PTC_3_6())
Observable('PTC_4_1_obs', PTC_4_1())
Observable('PTC_4_2_obs', PTC_4_2())
Observable('PTC_4_3_obs', PTC_4_3())
Observable('PTC_4_4_obs', PTC_4_4())
Observable('PTC_4_5_obs', PTC_4_5())
Observable('PTC_4_6_obs', PTC_4_6())
Observable('ci_1_obs', ci_1())
Observable('ci_2_obs', ci_2())
Observable('ci_3_obs', ci_3())
Observable('ci_4_obs', ci_4())
Observable('CI_1_obs', CI_1())
Observable('CI_2_obs', CI_2())
Observable('CI_3_obs', CI_3())
Observable('CI_4_obs', CI_4())
Observable('CN_1_obs', CN_1())
Observable('CN_2_obs', CN_2())
Observable('CN_3_obs', CN_3())
Observable('CN_4_obs', CN_4())
Observable('hh_1_obs', hh_1())
Observable('hh_2_obs', hh_2())
Observable('hh_3_obs', hh_3())
Observable('hh_4_obs', hh_4())
Observable('HH_1_1_obs', HH_1_1())
Observable('HH_1_2_obs', HH_1_2())
Observable('HH_1_3_obs', HH_1_3())
Observable('HH_1_4_obs', HH_1_4())
Observable('HH_1_5_obs', HH_1_5())
Observable('HH_1_6_obs', HH_1_6())
Observable('HH_2_1_obs', HH_2_1())
Observable('HH_2_2_obs', HH_2_2())
Observable('HH_2_3_obs', HH_2_3())
Observable('HH_2_4_obs', HH_2_4())
Observable('HH_2_5_obs', HH_2_5())
Observable('HH_2_6_obs', HH_2_6())
Observable('HH_3_1_obs', HH_3_1())
Observable('HH_3_2_obs', HH_3_2())
Observable('HH_3_3_obs', HH_3_3())
Observable('HH_3_4_obs', HH_3_4())
Observable('HH_3_5_obs', HH_3_5())
Observable('HH_3_6_obs', HH_3_6())
Observable('HH_4_1_obs', HH_4_1())
Observable('HH_4_2_obs', HH_4_2())
Observable('HH_4_3_obs', HH_4_3())
Observable('HH_4_4_obs', HH_4_4())
Observable('HH_4_5_obs', HH_4_5())
Observable('HH_4_6_obs', HH_4_6())
Observable('PH_1_1_obs', PH_1_1())
Observable('PH_1_2_obs', PH_1_2())
Observable('PH_1_3_obs', PH_1_3())
Observable('PH_1_4_obs', PH_1_4())
Observable('PH_1_5_obs', PH_1_5())
Observable('PH_1_6_obs', PH_1_6())
Observable('PH_2_1_obs', PH_2_1())
Observable('PH_2_2_obs', PH_2_2())
Observable('PH_2_3_obs', PH_2_3())
Observable('PH_2_4_obs', PH_2_4())
Observable('PH_2_5_obs', PH_2_5())
Observable('PH_2_6_obs', PH_2_6())
Observable('PH_3_1_obs', PH_3_1())
Observable('PH_3_2_obs', PH_3_2())
Observable('PH_3_3_obs', PH_3_3())
Observable('PH_3_4_obs', PH_3_4())
Observable('PH_3_5_obs', PH_3_5())
Observable('PH_3_6_obs', PH_3_6())
Observable('PH_4_1_obs', PH_4_1())
Observable('PH_4_2_obs', PH_4_2())
Observable('PH_4_3_obs', PH_4_3())
Observable('PH_4_4_obs', PH_4_4())
Observable('PH_4_5_obs', PH_4_5())
Observable('PH_4_6_obs', PH_4_6())

# Functions
#===============================================================================
# def Hill(label, K, nu, obs): # takes an observable, a half-maximal concentration constant (K_XXyy) and a cooperativity coefficient (nu_XXyy)
#     return Expression('Hill_s%' % label, sympify('%s^%s/(%s^%s + %s^%s)') % (K.name, nu.name, k.name, nu.name, obs.name, nu.name))
# 
# def sum_nT(label, obs1, obs2, obs3, obs4, obs5, obs6):    
#     return Expression('sum_nT_s%' % label, sympify('%s + %s + %s + %s + %s + %s') % (obs1.name, obs2.name, obs3.name, obs4.name, obs5.name, obs6.name))
#     
# def sum_iT(label, obs1, obs2, obs3, obs4, obs5, obs6):
#     return Expression('sum_iT_s%' % label, sympify('%s + %s + %s + %s + %s + %s') % (obs1.name, obs2.name, obs3.name, obs4.name, obs5.name, obs6.name))
#===============================================================================

# Expressions and Rules

#### engrailed mRNA (en)

Expression('EWG_nT_1', EWG_1_4_obs + EWG_2_5_obs + EWG_2_6_obs + EWG_1_1_obs + EWG_4_2_obs + EWG_4_3_obs)
Expression('EWG_nT_2', EWG_2_4_obs + EWG_3_5_obs + EWG_3_6_obs + EWG_2_1_obs + EWG_1_2_obs + EWG_1_3_obs)
Expression('EWG_nT_3', EWG_3_4_obs + EWG_4_5_obs + EWG_4_6_obs + EWG_3_1_obs + EWG_2_2_obs + EWG_2_3_obs)
Expression('EWG_nT_4', EWG_4_4_obs + EWG_1_5_obs + EWG_1_6_obs + EWG_4_1_obs + EWG_3_2_obs + EWG_3_3_obs)
 
Expression('Hill_CNen_1', (K_CNen**nu_CNen)/(K_CNen**nu_CNen + CN_1_obs**nu_CNen))
Expression('Hill_CNen_2', (K_CNen**nu_CNen)/(K_CNen**nu_CNen + CN_2_obs**nu_CNen))
Expression('Hill_CNen_3', (K_CNen**nu_CNen)/(K_CNen**nu_CNen + CN_3_obs**nu_CNen))
Expression('Hill_CNen_4', (K_CNen**nu_CNen)/(K_CNen**nu_CNen + CN_4_obs**nu_CNen))
 
# Expression('Hill_EWG_nT_1', (H_en*(EWG_nT_1*Hill_CNen_1**nu_WGen))/(K_WGen**nu_WGen + (EWG_nT_1*Hill_CNen_1**nu_WGen)))
# Expression('Hill_EWG_nT_2', (H_en*(EWG_nT_2*Hill_CNen_2**nu_WGen))/(K_WGen**nu_WGen + (EWG_nT_2*Hill_CNen_2**nu_WGen)))
# Expression('Hill_EWG_nT_3', (H_en*(EWG_nT_3*Hill_CNen_3**nu_WGen))/(K_WGen**nu_WGen + (EWG_nT_3*Hill_CNen_3**nu_WGen)))
# Expression('Hill_EWG_nT_4', (H_en*(EWG_nT_4*Hill_CNen_4**nu_WGen))/(K_WGen**nu_WGen + (EWG_nT_4*Hill_CNen_4**nu_WGen)))

Expression('Hill_EWG_nT_1', (H_en*(EWG_nT_1*Hill_CNen_1)**nu_WGen)/(K_WGen**nu_WGen + (EWG_nT_1*Hill_CNen_1)**nu_WGen))
Expression('Hill_EWG_nT_2', (H_en*(EWG_nT_2*Hill_CNen_2)**nu_WGen)/(K_WGen**nu_WGen + (EWG_nT_2*Hill_CNen_2)**nu_WGen))
Expression('Hill_EWG_nT_3', (H_en*(EWG_nT_3*Hill_CNen_3)**nu_WGen)/(K_WGen**nu_WGen + (EWG_nT_3*Hill_CNen_3)**nu_WGen))
Expression('Hill_EWG_nT_4', (H_en*(EWG_nT_4*Hill_CNen_4)**nu_WGen)/(K_WGen**nu_WGen + (EWG_nT_4*Hill_CNen_4)**nu_WGen))

Rule('synthesize_en_1', None >> en_1(), Hill_EWG_nT_1)
Rule('synthesize_en_2', None >> en_2(), Hill_EWG_nT_2)
Rule('synthesize_en_3', None >> en_3(), Hill_EWG_nT_3)
Rule('synthesize_en_4', None >> en_4(), Hill_EWG_nT_4)

Rule('degrade_en_1', en_1() >> None, H_en)
Rule('degrade_en_2', en_2() >> None, H_en)
Rule('degrade_en_3', en_3() >> None, H_en)
Rule('degrade_en_4', en_4() >> None, H_en)

#### engrailed protein (EN)

Rule('synthesize_EN_1', en_1() >> en_1() + EN_1(), H_EN)
Rule('synthesize_EN_2', en_2() >> en_2() + EN_2(), H_EN)
Rule('synthesize_EN_3', en_3() >> en_3() + EN_3(), H_EN)
Rule('synthesize_EN_4', en_4() >> en_4() + EN_4(), H_EN)

Rule('degrade_EN_1', EN_1() >> None, H_EN)
Rule('degrade_EN_2', EN_2() >> None, H_EN)
Rule('degrade_EN_3', EN_3() >> None, H_EN)
Rule('degrade_EN_4', EN_4() >> None, H_EN)

#### wingless mRNA (wg)

Expression('Hill_CNwg_1', K_CNwg**nu_CNwg/(K_CNwg**nu_CNwg + CN_1_obs**nu_CNwg))
Expression('Hill_CNwg_2', K_CNwg**nu_CNwg/(K_CNwg**nu_CNwg + CN_2_obs**nu_CNwg))
Expression('Hill_CNwg_3', K_CNwg**nu_CNwg/(K_CNwg**nu_CNwg + CN_3_obs**nu_CNwg))
Expression('Hill_CNwg_4', K_CNwg**nu_CNwg/(K_CNwg**nu_CNwg + CN_4_obs**nu_CNwg))
 
#===============================================================================
# Expression('Hill_CIwg_1', (CI_1_obs*Hill_CNwg_1**nu_CIwg)/(K_CIwg**nu_CIwg + CI_1_obs*Hill_CNwg_1**nu_CIwg))
# Expression('Hill_CIwg_2', (CI_2_obs*Hill_CNwg_2**nu_CIwg)/(K_CIwg**nu_CIwg + CI_2_obs*Hill_CNwg_2**nu_CIwg))
# Expression('Hill_CIwg_3', (CI_3_obs*Hill_CNwg_3**nu_CIwg)/(K_CIwg**nu_CIwg + CI_3_obs*Hill_CNwg_3**nu_CIwg))
# Expression('Hill_CIwg_4', (CI_4_obs*Hill_CNwg_4**nu_CIwg)/(K_CIwg**nu_CIwg + CI_4_obs*Hill_CNwg_4**nu_CIwg))
#===============================================================================
 
Expression('Hill_CIwg_1', ((CI_1_obs*Hill_CNwg_1)**nu_CIwg)/(K_CIwg**nu_CIwg + (CI_1_obs*Hill_CNwg_1)**nu_CIwg))
Expression('Hill_CIwg_2', ((CI_2_obs*Hill_CNwg_2)**nu_CIwg)/(K_CIwg**nu_CIwg + (CI_2_obs*Hill_CNwg_2)**nu_CIwg))
Expression('Hill_CIwg_3', ((CI_3_obs*Hill_CNwg_3)**nu_CIwg)/(K_CIwg**nu_CIwg + (CI_3_obs*Hill_CNwg_3)**nu_CIwg))
Expression('Hill_CIwg_4', ((CI_4_obs*Hill_CNwg_4)**nu_CIwg)/(K_CIwg**nu_CIwg + (CI_4_obs*Hill_CNwg_4)**nu_CIwg))
 
Expression('Hill_IWGwg_1', (IWG_1_obs**nu_WGwg)/(K_WGwg**nu_WGwg + IWG_1_obs**nu_WGwg))
Expression('Hill_IWGwg_2', (IWG_2_obs**nu_WGwg)/(K_WGwg**nu_WGwg + IWG_2_obs**nu_WGwg))
Expression('Hill_IWGwg_3', (IWG_3_obs**nu_WGwg)/(K_WGwg**nu_WGwg + IWG_3_obs**nu_WGwg))
Expression('Hill_IWGwg_4', (IWG_4_obs**nu_WGwg)/(K_WGwg**nu_WGwg + IWG_4_obs**nu_WGwg))
 
Expression('wg_mess_1', H_wg*(alpha_CIwg*Hill_CIwg_1 + alpha_WGwg*Hill_IWGwg_1)/(1 + alpha_CIwg*Hill_CIwg_1 + alpha_WGwg*Hill_IWGwg_1))
Expression('wg_mess_2', H_wg*(alpha_CIwg*Hill_CIwg_2 + alpha_WGwg*Hill_IWGwg_2)/(1 + alpha_CIwg*Hill_CIwg_2 + alpha_WGwg*Hill_IWGwg_2))
Expression('wg_mess_3', H_wg*(alpha_CIwg*Hill_CIwg_3 + alpha_WGwg*Hill_IWGwg_3)/(1 + alpha_CIwg*Hill_CIwg_3 + alpha_WGwg*Hill_IWGwg_3))
Expression('wg_mess_4', H_wg*(alpha_CIwg*Hill_CIwg_4 + alpha_WGwg*Hill_IWGwg_4)/(1 + alpha_CIwg*Hill_CIwg_4 + alpha_WGwg*Hill_IWGwg_4))

#===============================================================================
# Expression('wg_mess_1', sympify("H_wg*(alpha_CIwg*(CI_1_obs*((K_CNwg**nu_CNwg)/(K_CNwg**nu_CNwg + CN_1_obs**nu_CNwg))**nu_CIwg/(K_CIwg**nu_CIwg + CI_1_obs*((K_CNwg**nu_CNwg)/(K_CNwg**nu_CNwg + CN_1_obs**nu_CNwg))**nu_CIwg)) + alpha_WGwg*(IWG_1_obs**nu_WGwg/(K_WGwg**nu_WGwg + IWG_1_obs**nu_WGwg)))/(1 + alpha_CIwg*(CI_1_obs*((K_CNwg**nu_CNwg)/(K_CNwg**nu_CNwg + CN_1_obs**nu_CNwg))**nu_CIwg/(K_CIwg**nu_CIwg + CI_1_obs*((K_CNwg**nu_CNwg)/(K_CNwg**nu_CNwg + CN_1_obs**nu_CNwg))**nu_CIwg)) + alpha_WGwg*(IWG_1_obs**nu_WGwg/(K_WGwg**nu_WGwg + IWG_1_obs**nu_WGwg)))"))
# Expression('wg_mess_2', sympify("H_wg*(alpha_CIwg*(CI_2_obs*((K_CNwg**nu_CNwg)/(K_CNwg**nu_CNwg + CN_2_obs**nu_CNwg))**nu_CIwg/(K_CIwg**nu_CIwg + CI_2_obs*((K_CNwg**nu_CNwg)/(K_CNwg**nu_CNwg + CN_2_obs**nu_CNwg))**nu_CIwg)) + alpha_WGwg*(IWG_2_obs**nu_WGwg/(K_WGwg**nu_WGwg + IWG_2_obs**nu_WGwg)))/(1 + alpha_CIwg*(CI_2_obs*((K_CNwg**nu_CNwg)/(K_CNwg**nu_CNwg + CN_2_obs**nu_CNwg))**nu_CIwg/(K_CIwg**nu_CIwg + CI_2_obs*((K_CNwg**nu_CNwg)/(K_CNwg**nu_CNwg + CN_2_obs**nu_CNwg))**nu_CIwg)) + alpha_WGwg*(IWG_2_obs**nu_WGwg/(K_WGwg**nu_WGwg + IWG_2_obs**nu_WGwg)))"))
# Expression('wg_mess_3', sympify("H_wg*(alpha_CIwg*(CI_3_obs*((K_CNwg**nu_CNwg)/(K_CNwg**nu_CNwg + CN_3_obs**nu_CNwg))**nu_CIwg/(K_CIwg**nu_CIwg + CI_3_obs*((K_CNwg**nu_CNwg)/(K_CNwg**nu_CNwg + CN_3_obs**nu_CNwg))**nu_CIwg)) + alpha_WGwg*(IWG_3_obs**nu_WGwg/(K_WGwg**nu_WGwg + IWG_3_obs**nu_WGwg)))/(1 + alpha_CIwg*(CI_3_obs*((K_CNwg**nu_CNwg)/(K_CNwg**nu_CNwg + CN_3_obs**nu_CNwg))**nu_CIwg/(K_CIwg**nu_CIwg + CI_3_obs*((K_CNwg**nu_CNwg)/(K_CNwg**nu_CNwg + CN_3_obs**nu_CNwg))**nu_CIwg)) + alpha_WGwg*(IWG_3_obs**nu_WGwg/(K_WGwg**nu_WGwg + IWG_3_obs**nu_WGwg)))"))
# Expression('wg_mess_4', sympify("H_wg*(alpha_CIwg*(CI_4_obs*((K_CNwg**nu_CNwg)/(K_CNwg**nu_CNwg + CN_4_obs**nu_CNwg))**nu_CIwg/(K_CIwg**nu_CIwg + CI_4_obs*((K_CNwg**nu_CNwg)/(K_CNwg**nu_CNwg + CN_4_obs**nu_CNwg))**nu_CIwg)) + alpha_WGwg*(IWG_4_obs**nu_WGwg/(K_WGwg**nu_WGwg + IWG_4_obs**nu_WGwg)))/(1 + alpha_CIwg*(CI_4_obs*((K_CNwg**nu_CNwg)/(K_CNwg**nu_CNwg + CN_4_obs**nu_CNwg))**nu_CIwg/(K_CIwg**nu_CIwg + CI_4_obs*((K_CNwg**nu_CNwg)/(K_CNwg**nu_CNwg + CN_4_obs**nu_CNwg))**nu_CIwg)) + alpha_WGwg*(IWG_4_obs**nu_WGwg/(K_WGwg**nu_WGwg + IWG_4_obs**nu_WGwg)))"))
#===============================================================================

Rule('synthesize_wg_1', None >> wg_1(), wg_mess_1)
Rule('synthesize_wg_2', None >> wg_2(), wg_mess_2)
Rule('synthesize_wg_3', None >> wg_3(), wg_mess_3)
Rule('synthesize_wg_4', None >> wg_4(), wg_mess_4)

Rule('degrade_wg_1', wg_1() >> None, H_wg)
Rule('degrade_wg_2', wg_2() >> None, H_wg)
Rule('degrade_wg_3', wg_3() >> None, H_wg)
Rule('degrade_wg_4', wg_4() >> None, H_wg)

#### wingless protein: intracellular (IWG) & extracellular (EWG)

# synthesis & degradation

Rule('synthesize_IWG_1', wg_1() >> wg_1() + IWG_1(), H_IWG)
Rule('synthesize_IWG_2', wg_2() >> wg_2() + IWG_2(), H_IWG)
Rule('synthesize_IWG_3', wg_3() >> wg_3() + IWG_3(), H_IWG)
Rule('synthesize_IWG_4', wg_4() >> wg_4() + IWG_4(), H_IWG)

Rule('degrade_IWG_1', IWG_1() >> None, H_IWG)
Rule('degrade_IWG_2', IWG_2() >> None, H_IWG)
Rule('degrade_IWG_3', IWG_3() >> None, H_IWG)
Rule('degrade_IWG_4', IWG_4() >> None, H_IWG)

Rule('degrade_EWG_1_1', EWG_1_1() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_1_2', EWG_1_2() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_1_3', EWG_1_3() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_1_4', EWG_1_4() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_1_5', EWG_1_5() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_1_6', EWG_1_6() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_2_1', EWG_2_1() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_2_2', EWG_2_2() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_2_3', EWG_2_3() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_2_4', EWG_2_4() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_2_5', EWG_2_5() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_2_6', EWG_2_6() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_3_1', EWG_3_1() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_3_2', EWG_3_2() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_3_3', EWG_3_3() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_3_4', EWG_3_4() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_3_5', EWG_3_5() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_3_6', EWG_3_6() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_4_1', EWG_4_1() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_4_2', EWG_4_2() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_4_3', EWG_4_3() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_4_4', EWG_4_4() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_4_5', EWG_4_5() >> None, H_EWG) #H_IWG)
Rule('degrade_EWG_4_6', EWG_4_6() >> None, H_EWG) #H_IWG)

# endocytosis and exocytosis

Rule('endo_exo_WG_1_1', EWG_1_1() | IWG_1(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_1_2', EWG_1_2() | IWG_1(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_1_3', EWG_1_3() | IWG_1(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_1_4', EWG_1_4() | IWG_1(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_1_5', EWG_1_5() | IWG_1(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_1_6', EWG_1_6() | IWG_1(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_2_1', EWG_2_1() | IWG_2(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_2_2', EWG_2_2() | IWG_2(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_2_3', EWG_2_3() | IWG_2(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_2_4', EWG_2_4() | IWG_2(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_2_5', EWG_2_5() | IWG_2(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_2_6', EWG_2_6() | IWG_2(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_3_1', EWG_3_1() | IWG_3(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_3_2', EWG_3_2() | IWG_3(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_3_3', EWG_3_3() | IWG_3(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_3_4', EWG_3_4() | IWG_3(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_3_5', EWG_3_5() | IWG_3(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_3_6', EWG_3_6() | IWG_3(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_4_1', EWG_4_1() | IWG_4(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_4_2', EWG_4_2() | IWG_4(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_4_3', EWG_4_3() | IWG_4(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_4_4', EWG_4_4() | IWG_4(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_4_5', EWG_4_5() | IWG_4(), Endo_WG, Exo_WG)
Rule('endo_exo_WG_4_6', EWG_4_6() | IWG_4(), Endo_WG, Exo_WG)

# diffusion between faces: around the perimeter

Rule('diffuse_EWG_1_1_2', EWG_1_1() | EWG_1_2(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_1_2_3', EWG_1_2() | EWG_1_3(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_1_3_4', EWG_1_3() | EWG_1_4(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_1_4_5', EWG_1_4() | EWG_1_5(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_1_5_6', EWG_1_5() | EWG_1_6(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_1_6_1', EWG_1_6() | EWG_1_1(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_2_1_2', EWG_2_1() | EWG_2_2(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_2_2_3', EWG_2_2() | EWG_2_3(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_2_3_4', EWG_2_3() | EWG_2_4(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_2_4_5', EWG_2_4() | EWG_2_5(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_2_5_6', EWG_2_5() | EWG_2_6(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_2_6_1', EWG_2_6() | EWG_2_1(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_3_1_2', EWG_3_1() | EWG_3_2(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_3_2_3', EWG_3_2() | EWG_3_3(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_3_3_4', EWG_3_3() | EWG_3_4(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_3_4_5', EWG_3_4() | EWG_3_5(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_3_5_6', EWG_3_5() | EWG_3_6(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_3_6_1', EWG_3_6() | EWG_3_1(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_4_1_2', EWG_4_1() | EWG_4_2(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_4_2_3', EWG_4_2() | EWG_4_3(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_4_3_4', EWG_4_3() | EWG_4_4(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_4_4_5', EWG_4_4() | EWG_4_5(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_4_5_6', EWG_4_5() | EWG_4_6(), LMxfer_WG, LMxfer_WG)
Rule('diffuse_EWG_4_6_1', EWG_4_6() | EWG_4_1(), LMxfer_WG, LMxfer_WG)

# diffusion between faces: cell to cell

Rule('diffuse_EWG_1_1_1_4', EWG_1_1() | EWG_1_4(), Mxfer_WG, Mxfer_WG)
Rule('diffuse_EWG_1_2_2_5', EWG_1_2() | EWG_2_5(), Mxfer_WG, Mxfer_WG)
Rule('diffuse_EWG_1_3_2_6', EWG_1_3() | EWG_2_6(), Mxfer_WG, Mxfer_WG)
Rule('diffuse_EWG_1_5_4_2', EWG_1_5() | EWG_4_2(), Mxfer_WG, Mxfer_WG)
Rule('diffuse_EWG_1_6_4_3', EWG_1_6() | EWG_4_3(), Mxfer_WG, Mxfer_WG)
Rule('diffuse_EWG_2_1_2_4', EWG_2_1() | EWG_2_4(), Mxfer_WG, Mxfer_WG)
Rule('diffuse_EWG_2_2_3_5', EWG_2_2() | EWG_3_5(), Mxfer_WG, Mxfer_WG)
Rule('diffuse_EWG_2_3_3_6', EWG_2_3() | EWG_3_6(), Mxfer_WG, Mxfer_WG)
Rule('diffuse_EWG_3_1_3_4', EWG_3_1() | EWG_3_4(), Mxfer_WG, Mxfer_WG)
Rule('diffuse_EWG_3_2_4_5', EWG_3_2() | EWG_4_5(), Mxfer_WG, Mxfer_WG)
Rule('diffuse_EWG_3_3_4_6', EWG_3_3() | EWG_4_6(), Mxfer_WG, Mxfer_WG)
Rule('diffuse_EWG_4_1_4_4', EWG_4_1() | EWG_4_4(), Mxfer_WG, Mxfer_WG)

#### patched mRNA (ptc)

Expression('Hill_CNptc_1', (K_CNptc**nu_CNptc)/(K_CNptc**nu_CNptc + CN_1_obs**nu_CNptc))
Expression('Hill_CNptc_2', (K_CNptc**nu_CNptc)/(K_CNptc**nu_CNptc + CN_2_obs**nu_CNptc))
Expression('Hill_CNptc_3', (K_CNptc**nu_CNptc)/(K_CNptc**nu_CNptc + CN_3_obs**nu_CNptc))
Expression('Hill_CNptc_4', (K_CNptc**nu_CNptc)/(K_CNptc**nu_CNptc + CN_4_obs**nu_CNptc))
 
Expression('Hill_CIptc_1', H_ptc*(CI_1_obs*Hill_CNptc_1)**nu_CIptc/(K_CIptc**nu_CIptc + (CI_1_obs*Hill_CNptc_1)**nu_CIptc))
Expression('Hill_CIptc_2', H_ptc*(CI_2_obs*Hill_CNptc_2)**nu_CIptc/(K_CIptc**nu_CIptc + (CI_2_obs*Hill_CNptc_2)**nu_CIptc))
Expression('Hill_CIptc_3', H_ptc*(CI_3_obs*Hill_CNptc_3)**nu_CIptc/(K_CIptc**nu_CIptc + (CI_3_obs*Hill_CNptc_3)**nu_CIptc))
Expression('Hill_CIptc_4', H_ptc*(CI_4_obs*Hill_CNptc_4)**nu_CIptc/(K_CIptc**nu_CIptc + (CI_4_obs*Hill_CNptc_4)**nu_CIptc))

#===============================================================================
# Expression('Hill_CIptc_1', sympify("H_ptc*CI_1_obs*(K_CNptc**nu_CNptc/(K_CNptc**nu_CNptc + CN_1_obs**nu_CNptc))**nu_CIptc/(K_CIptc**nu_CIptc + CI_1_obs*(K_CNptc**nu_CNptc/(K_CNptc**nu_CNptc + CN_1_obs**nu_CNptc))**nu_CIptc)"))
# Expression('Hill_CIptc_2', sympify("H_ptc*CI_2_obs*(K_CNptc**nu_CNptc/(K_CNptc**nu_CNptc + CN_2_obs**nu_CNptc))**nu_CIptc/(K_CIptc**nu_CIptc + CI_2_obs*(K_CNptc**nu_CNptc/(K_CNptc**nu_CNptc + CN_2_obs**nu_CNptc))**nu_CIptc)"))
# Expression('Hill_CIptc_3', sympify("H_ptc*CI_3_obs*(K_CNptc**nu_CNptc/(K_CNptc**nu_CNptc + CN_3_obs**nu_CNptc))**nu_CIptc/(K_CIptc**nu_CIptc + CI_3_obs*(K_CNptc**nu_CNptc/(K_CNptc**nu_CNptc + CN_3_obs**nu_CNptc))**nu_CIptc)"))
# Expression('Hill_CIptc_4', sympify("H_ptc*CI_4_obs*(K_CNptc**nu_CNptc/(K_CNptc**nu_CNptc + CN_4_obs**nu_CNptc))**nu_CIptc/(K_CIptc**nu_CIptc + CI_4_obs*(K_CNptc**nu_CNptc/(K_CNptc**nu_CNptc + CN_4_obs**nu_CNptc))**nu_CIptc)"))
#===============================================================================

Rule('synthesize_ptc_1', None >> ptc_1(), Hill_CIptc_1)
Rule('synthesize_ptc_2', None >> ptc_2(), Hill_CIptc_2)
Rule('synthesize_ptc_3', None >> ptc_3(), Hill_CIptc_3)
Rule('synthesize_ptc_4', None >> ptc_4(), Hill_CIptc_4)

Rule('degrade_ptc_1', ptc_1() >> None, H_ptc)
Rule('degrade_ptc_2', ptc_2() >> None, H_ptc)
Rule('degrade_ptc_3', ptc_3() >> None, H_ptc)
Rule('degrade_ptc_4', ptc_4() >> None, H_ptc)

#### patched protein (PTC)

# synthesis and degradation

Rule('synthesize_PTC_1_1', ptc_1() >> ptc_1() + PTC_1_1(), H_PTC_6th)
Rule('synthesize_PTC_1_2', ptc_1() >> ptc_1() + PTC_1_2(), H_PTC_6th)
Rule('synthesize_PTC_1_3', ptc_1() >> ptc_1() + PTC_1_3(), H_PTC_6th)
Rule('synthesize_PTC_1_4', ptc_1() >> ptc_1() + PTC_1_4(), H_PTC_6th)
Rule('synthesize_PTC_1_5', ptc_1() >> ptc_1() + PTC_1_5(), H_PTC_6th)
Rule('synthesize_PTC_1_6', ptc_1() >> ptc_1() + PTC_1_6(), H_PTC_6th)
Rule('synthesize_PTC_2_1', ptc_2() >> ptc_2() + PTC_2_1(), H_PTC_6th)
Rule('synthesize_PTC_2_2', ptc_2() >> ptc_2() + PTC_2_2(), H_PTC_6th)
Rule('synthesize_PTC_2_3', ptc_2() >> ptc_2() + PTC_2_3(), H_PTC_6th)
Rule('synthesize_PTC_2_4', ptc_2() >> ptc_2() + PTC_2_4(), H_PTC_6th)
Rule('synthesize_PTC_2_5', ptc_2() >> ptc_2() + PTC_2_5(), H_PTC_6th)
Rule('synthesize_PTC_2_6', ptc_2() >> ptc_2() + PTC_2_6(), H_PTC_6th)
Rule('synthesize_PTC_3_1', ptc_3() >> ptc_3() + PTC_3_1(), H_PTC_6th)
Rule('synthesize_PTC_3_2', ptc_3() >> ptc_3() + PTC_3_2(), H_PTC_6th)
Rule('synthesize_PTC_3_3', ptc_3() >> ptc_3() + PTC_3_3(), H_PTC_6th)
Rule('synthesize_PTC_3_4', ptc_3() >> ptc_3() + PTC_3_4(), H_PTC_6th)
Rule('synthesize_PTC_3_5', ptc_3() >> ptc_3() + PTC_3_5(), H_PTC_6th)
Rule('synthesize_PTC_3_6', ptc_3() >> ptc_3() + PTC_3_6(), H_PTC_6th)
Rule('synthesize_PTC_4_1', ptc_4() >> ptc_4() + PTC_4_1(), H_PTC_6th)
Rule('synthesize_PTC_4_2', ptc_4() >> ptc_4() + PTC_4_2(), H_PTC_6th)
Rule('synthesize_PTC_4_3', ptc_4() >> ptc_4() + PTC_4_3(), H_PTC_6th)
Rule('synthesize_PTC_4_4', ptc_4() >> ptc_4() + PTC_4_4(), H_PTC_6th)
Rule('synthesize_PTC_4_5', ptc_4() >> ptc_4() + PTC_4_5(), H_PTC_6th)
Rule('synthesize_PTC_4_6', ptc_4() >> ptc_4() + PTC_4_6(), H_PTC_6th)

Rule('degrade_PTC_1_1', PTC_1_1() >> None, H_PTC)
Rule('degrade_PTC_1_2', PTC_1_2() >> None, H_PTC)
Rule('degrade_PTC_1_3', PTC_1_3() >> None, H_PTC)
Rule('degrade_PTC_1_4', PTC_1_4() >> None, H_PTC)
Rule('degrade_PTC_1_5', PTC_1_5() >> None, H_PTC)
Rule('degrade_PTC_1_6', PTC_1_6() >> None, H_PTC)
Rule('degrade_PTC_2_1', PTC_2_1() >> None, H_PTC)
Rule('degrade_PTC_2_2', PTC_2_2() >> None, H_PTC)
Rule('degrade_PTC_2_3', PTC_2_3() >> None, H_PTC)
Rule('degrade_PTC_2_4', PTC_2_4() >> None, H_PTC)
Rule('degrade_PTC_2_5', PTC_2_5() >> None, H_PTC)
Rule('degrade_PTC_2_6', PTC_2_6() >> None, H_PTC)
Rule('degrade_PTC_3_1', PTC_3_1() >> None, H_PTC)
Rule('degrade_PTC_3_2', PTC_3_2() >> None, H_PTC)
Rule('degrade_PTC_3_3', PTC_3_3() >> None, H_PTC)
Rule('degrade_PTC_3_4', PTC_3_4() >> None, H_PTC)
Rule('degrade_PTC_3_5', PTC_3_5() >> None, H_PTC)
Rule('degrade_PTC_3_6', PTC_3_6() >> None, H_PTC)
Rule('degrade_PTC_4_1', PTC_4_1() >> None, H_PTC)
Rule('degrade_PTC_4_2', PTC_4_2() >> None, H_PTC)
Rule('degrade_PTC_4_3', PTC_4_3() >> None, H_PTC)
Rule('degrade_PTC_4_4', PTC_4_4() >> None, H_PTC)
Rule('degrade_PTC_4_5', PTC_4_5() >> None, H_PTC)
Rule('degrade_PTC_4_6', PTC_4_6() >> None, H_PTC)

# complexation: re-dimensionalization will allow for simplification of the second order equations involving PTC, HH, and PH 

Expression('PTC_1_1_2nd_order', K_PTC_HH*max_HH*HH_1_4_obs) #*PTC_1_1_obs)
Expression('PTC_1_2_2nd_order', K_PTC_HH*max_HH*HH_2_5_obs) #*PTC_1_2_obs)
Expression('PTC_1_3_2nd_order', K_PTC_HH*max_HH*HH_2_6_obs) #*PTC_1_3_obs)
Expression('PTC_1_4_2nd_order', K_PTC_HH*max_HH*HH_1_1_obs) #*PTC_1_4_obs)
Expression('PTC_1_5_2nd_order', K_PTC_HH*max_HH*HH_4_2_obs) #*PTC_1_5_obs)
Expression('PTC_1_6_2nd_order', K_PTC_HH*max_HH*HH_4_3_obs) #*PTC_1_6_obs)
Expression('PTC_2_1_2nd_order', K_PTC_HH*max_HH*HH_2_4_obs) #*PTC_2_1_obs)
Expression('PTC_2_2_2nd_order', K_PTC_HH*max_HH*HH_3_5_obs) #*PTC_2_2_obs)
Expression('PTC_2_3_2nd_order', K_PTC_HH*max_HH*HH_3_6_obs) #*PTC_2_3_obs)
Expression('PTC_2_4_2nd_order', K_PTC_HH*max_HH*HH_2_1_obs) #*PTC_2_4_obs)
Expression('PTC_2_5_2nd_order', K_PTC_HH*max_HH*HH_1_2_obs) #*PTC_2_5_obs)
Expression('PTC_2_6_2nd_order', K_PTC_HH*max_HH*HH_1_3_obs) #*PTC_2_6_obs)
Expression('PTC_3_1_2nd_order', K_PTC_HH*max_HH*HH_3_4_obs) #*PTC_3_1_obs)
Expression('PTC_3_2_2nd_order', K_PTC_HH*max_HH*HH_4_5_obs) #*PTC_3_2_obs)
Expression('PTC_3_3_2nd_order', K_PTC_HH*max_HH*HH_4_6_obs) #*PTC_3_3_obs)
Expression('PTC_3_4_2nd_order', K_PTC_HH*max_HH*HH_3_1_obs) #*PTC_3_4_obs)
Expression('PTC_3_5_2nd_order', K_PTC_HH*max_HH*HH_2_2_obs) #*PTC_3_5_obs)
Expression('PTC_3_6_2nd_order', K_PTC_HH*max_HH*HH_2_3_obs) #*PTC_3_6_obs)
Expression('PTC_4_1_2nd_order', K_PTC_HH*max_HH*HH_4_4_obs) #*PTC_4_1_obs)
Expression('PTC_4_2_2nd_order', K_PTC_HH*max_HH*HH_1_5_obs) #*PTC_4_2_obs)
Expression('PTC_4_3_2nd_order', K_PTC_HH*max_HH*HH_1_6_obs) #*PTC_4_3_obs)
Expression('PTC_4_4_2nd_order', K_PTC_HH*max_HH*HH_4_1_obs) #*PTC_4_4_obs)
Expression('PTC_4_5_2nd_order', K_PTC_HH*max_HH*HH_3_2_obs) #*PTC_4_5_obs)
Expression('PTC_4_6_2nd_order', K_PTC_HH*max_HH*HH_3_3_obs) #*PTC_4_6_obs)

#===============================================================================
# Expression('PTC_1_1_2nd_order', sympify("K_PTC_HH*max_HH*HH_1_4_obs*PTC_1_1_obs"))
# Expression('PTC_1_2_2nd_order', sympify("K_PTC_HH*max_HH*HH_2_5_obs*PTC_1_2_obs"))
# Expression('PTC_1_3_2nd_order', sympify("K_PTC_HH*max_HH*HH_2_6_obs*PTC_1_3_obs"))
# Expression('PTC_1_4_2nd_order', sympify("K_PTC_HH*max_HH*HH_1_1_obs*PTC_1_4_obs"))
# Expression('PTC_1_5_2nd_order', sympify("K_PTC_HH*max_HH*HH_4_2_obs*PTC_1_5_obs"))
# Expression('PTC_1_6_2nd_order', sympify("K_PTC_HH*max_HH*HH_4_3_obs*PTC_1_6_obs"))
# Expression('PTC_2_1_2nd_order', sympify("K_PTC_HH*max_HH*HH_2_4_obs*PTC_2_1_obs"))
# Expression('PTC_2_2_2nd_order', sympify("K_PTC_HH*max_HH*HH_3_5_obs*PTC_2_2_obs"))
# Expression('PTC_2_3_2nd_order', sympify("K_PTC_HH*max_HH*HH_3_6_obs*PTC_2_3_obs"))
# Expression('PTC_2_4_2nd_order', sympify("K_PTC_HH*max_HH*HH_2_1_obs*PTC_2_4_obs"))
# Expression('PTC_2_5_2nd_order', sympify("K_PTC_HH*max_HH*HH_1_2_obs*PTC_2_5_obs"))
# Expression('PTC_2_6_2nd_order', sympify("K_PTC_HH*max_HH*HH_1_3_obs*PTC_2_6_obs"))
# Expression('PTC_3_1_2nd_order', sympify("K_PTC_HH*max_HH*HH_3_4_obs*PTC_3_1_obs"))
# Expression('PTC_3_2_2nd_order', sympify("K_PTC_HH*max_HH*HH_4_5_obs*PTC_3_2_obs"))
# Expression('PTC_3_3_2nd_order', sympify("K_PTC_HH*max_HH*HH_4_6_obs*PTC_3_3_obs"))
# Expression('PTC_3_4_2nd_order', sympify("K_PTC_HH*max_HH*HH_3_1_obs*PTC_3_4_obs"))
# Expression('PTC_3_5_2nd_order', sympify("K_PTC_HH*max_HH*HH_2_2_obs*PTC_3_5_obs"))
# Expression('PTC_3_6_2nd_order', sympify("K_PTC_HH*max_HH*HH_2_3_obs*PTC_3_6_obs"))
# Expression('PTC_4_1_2nd_order', sympify("K_PTC_HH*max_HH*HH_4_4_obs*PTC_4_1_obs"))
# Expression('PTC_4_2_2nd_order', sympify("K_PTC_HH*max_HH*HH_1_5_obs*PTC_4_2_obs"))
# Expression('PTC_4_3_2nd_order', sympify("K_PTC_HH*max_HH*HH_1_6_obs*PTC_4_3_obs"))
# Expression('PTC_4_4_2nd_order', sympify("K_PTC_HH*max_HH*HH_4_1_obs*PTC_4_4_obs"))
# Expression('PTC_4_5_2nd_order', sympify("K_PTC_HH*max_HH*HH_3_2_obs*PTC_4_5_obs"))
# Expression('PTC_4_6_2nd_order', sympify("K_PTC_HH*max_HH*HH_3_3_obs*PTC_4_6_obs"))
#===============================================================================

Rule('PTC_to_PH_1_1', PTC_1_1() >> None, PTC_1_1_2nd_order)
Rule('PTC_to_PH_1_2', PTC_1_2() >> None, PTC_1_2_2nd_order)
Rule('PTC_to_PH_1_3', PTC_1_3() >> None, PTC_1_3_2nd_order)
Rule('PTC_to_PH_1_4', PTC_1_4() >> None, PTC_1_4_2nd_order)
Rule('PTC_to_PH_1_5', PTC_1_5() >> None, PTC_1_5_2nd_order)
Rule('PTC_to_PH_1_6', PTC_1_6() >> None, PTC_1_6_2nd_order)
Rule('PTC_to_PH_2_1', PTC_2_1() >> None, PTC_2_1_2nd_order)
Rule('PTC_to_PH_2_2', PTC_2_2() >> None, PTC_2_2_2nd_order)
Rule('PTC_to_PH_2_3', PTC_2_3() >> None, PTC_2_3_2nd_order)
Rule('PTC_to_PH_2_4', PTC_2_4() >> None, PTC_2_4_2nd_order)
Rule('PTC_to_PH_2_5', PTC_2_5() >> None, PTC_2_5_2nd_order)
Rule('PTC_to_PH_2_6', PTC_2_6() >> None, PTC_2_6_2nd_order)
Rule('PTC_to_PH_3_1', PTC_3_1() >> None, PTC_3_1_2nd_order)
Rule('PTC_to_PH_3_2', PTC_3_2() >> None, PTC_3_2_2nd_order)
Rule('PTC_to_PH_3_3', PTC_3_3() >> None, PTC_3_3_2nd_order)
Rule('PTC_to_PH_3_4', PTC_3_4() >> None, PTC_3_4_2nd_order)
Rule('PTC_to_PH_3_5', PTC_3_5() >> None, PTC_3_5_2nd_order)
Rule('PTC_to_PH_3_6', PTC_3_6() >> None, PTC_3_6_2nd_order)
Rule('PTC_to_PH_4_1', PTC_4_1() >> None, PTC_4_1_2nd_order)
Rule('PTC_to_PH_4_2', PTC_4_2() >> None, PTC_4_2_2nd_order)
Rule('PTC_to_PH_4_3', PTC_4_3() >> None, PTC_4_3_2nd_order)
Rule('PTC_to_PH_4_4', PTC_4_4() >> None, PTC_4_4_2nd_order)
Rule('PTC_to_PH_4_5', PTC_4_5() >> None, PTC_4_5_2nd_order)
Rule('PTC_to_PH_4_6', PTC_4_6() >> None, PTC_4_6_2nd_order)

# diffusion between faces: around the perimeter

Rule('diffuse_PTC_1_1_2', PTC_1_1() | PTC_1_2(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_1_2_3', PTC_1_2() | PTC_1_3(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_1_3_4', PTC_1_3() | PTC_1_4(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_1_4_5', PTC_1_4() | PTC_1_5(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_1_5_6', PTC_1_5() | PTC_1_6(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_1_6_1', PTC_1_6() | PTC_1_1(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_2_1_2', PTC_2_1() | PTC_2_2(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_2_2_3', PTC_2_2() | PTC_2_3(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_2_3_4', PTC_2_3() | PTC_2_4(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_2_4_5', PTC_2_4() | PTC_2_5(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_2_5_6', PTC_2_5() | PTC_2_6(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_2_6_1', PTC_2_6() | PTC_2_1(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_3_1_2', PTC_3_1() | PTC_3_2(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_3_2_3', PTC_3_2() | PTC_3_3(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_3_3_4', PTC_3_3() | PTC_3_4(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_3_4_5', PTC_3_4() | PTC_3_5(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_3_5_6', PTC_3_5() | PTC_3_6(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_3_6_1', PTC_3_6() | PTC_3_1(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_4_1_2', PTC_4_1() | PTC_4_2(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_4_2_3', PTC_4_2() | PTC_4_3(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_4_3_4', PTC_4_3() | PTC_4_4(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_4_4_5', PTC_4_4() | PTC_4_5(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_4_5_6', PTC_4_5() | PTC_4_6(), LMxfer_PTC, LMxfer_PTC)
Rule('diffuse_PTC_4_6_1', PTC_4_6() | PTC_4_1(), LMxfer_PTC, LMxfer_PTC)

#### hedgehog mRNA (hh)

Expression('Hill_CNhh_1', K_CNhh**nu_CNhh/(K_CNhh**nu_CNhh + CN_1_obs**nu_CNhh))
Expression('Hill_CNhh_2', K_CNhh**nu_CNhh/(K_CNhh**nu_CNhh + CN_2_obs**nu_CNhh))
Expression('Hill_CNhh_3', K_CNhh**nu_CNhh/(K_CNhh**nu_CNhh + CN_3_obs**nu_CNhh))
Expression('Hill_CNhh_4', K_CNhh**nu_CNhh/(K_CNhh**nu_CNhh + CN_4_obs**nu_CNhh))
 
Expression('Hill_ENhh_1', H_hh*(EN_1_obs*Hill_CNhh_1)**nu_ENhh/(K_ENhh**nu_ENhh + (EN_1_obs*Hill_CNhh_1)**nu_ENhh))
Expression('Hill_ENhh_2', H_hh*(EN_2_obs*Hill_CNhh_2)**nu_ENhh/(K_ENhh**nu_ENhh + (EN_2_obs*Hill_CNhh_2)**nu_ENhh))
Expression('Hill_ENhh_3', H_hh*(EN_3_obs*Hill_CNhh_3)**nu_ENhh/(K_ENhh**nu_ENhh + (EN_3_obs*Hill_CNhh_3)**nu_ENhh))
Expression('Hill_ENhh_4', H_hh*(EN_4_obs*Hill_CNhh_4)**nu_ENhh/(K_ENhh**nu_ENhh + (EN_4_obs*Hill_CNhh_4)**nu_ENhh))

#===============================================================================
# Expression('Hill_ENhh_1', sympify("H_hh*EN_1_obs*(K_CNhh**nu_CNhh/(K_CNhh**nu_CNhh + CN_1_obs**nu_CNhh))**nu_ENhh/(K_ENhh**nu_ENhh + EN_1_obs*(K_CNhh**nu_CNhh/(K_CNhh**nu_CNhh + CN_1_obs**nu_CNhh))**nu_ENhh)"))
# Expression('Hill_ENhh_2', sympify("H_hh*EN_2_obs*(K_CNhh**nu_CNhh/(K_CNhh**nu_CNhh + CN_2_obs**nu_CNhh))**nu_ENhh/(K_ENhh**nu_ENhh + EN_2_obs*(K_CNhh**nu_CNhh/(K_CNhh**nu_CNhh + CN_2_obs**nu_CNhh))**nu_ENhh)"))
# Expression('Hill_ENhh_3', sympify("H_hh*EN_3_obs*(K_CNhh**nu_CNhh/(K_CNhh**nu_CNhh + CN_3_obs**nu_CNhh))**nu_ENhh/(K_ENhh**nu_ENhh + EN_3_obs*(K_CNhh**nu_CNhh/(K_CNhh**nu_CNhh + CN_3_obs**nu_CNhh))**nu_ENhh)"))
# Expression('Hill_ENhh_4', sympify("H_hh*EN_4_obs*(K_CNhh**nu_CNhh/(K_CNhh**nu_CNhh + CN_4_obs**nu_CNhh))**nu_ENhh/(K_ENhh**nu_ENhh + EN_4_obs*(K_CNhh**nu_CNhh/(K_CNhh**nu_CNhh + CN_4_obs**nu_CNhh))**nu_ENhh)"))
#===============================================================================

Rule('synthesize_hh_1', None >> hh_1(), Hill_ENhh_1)
Rule('synthesize_hh_2', None >> hh_2(), Hill_ENhh_2)
Rule('synthesize_hh_3', None >> hh_3(), Hill_ENhh_3)
Rule('synthesize_hh_4', None >> hh_4(), Hill_ENhh_4)

Rule('degrade_hh_1', hh_1() >> None, H_hh)
Rule('degrade_hh_2', hh_2() >> None, H_hh)
Rule('degrade_hh_3', hh_3() >> None, H_hh)
Rule('degrade_hh_4', hh_4() >> None, H_hh)

#### hedgehog protein (HH)

# synthesis and degradation

Rule('synthesize_HH_1_1', hh_1() >> hh_1() + HH_1_1(), H_HH_6th)
Rule('synthesize_HH_1_2', hh_1() >> hh_1() + HH_1_2(), H_HH_6th)
Rule('synthesize_HH_1_3', hh_1() >> hh_1() + HH_1_3(), H_HH_6th)
Rule('synthesize_HH_1_4', hh_1() >> hh_1() + HH_1_4(), H_HH_6th)
Rule('synthesize_HH_1_5', hh_1() >> hh_1() + HH_1_5(), H_HH_6th)
Rule('synthesize_HH_1_6', hh_1() >> hh_1() + HH_1_6(), H_HH_6th)
Rule('synthesize_HH_2_1', hh_2() >> hh_2() + HH_2_1(), H_HH_6th)
Rule('synthesize_HH_2_2', hh_2() >> hh_2() + HH_2_2(), H_HH_6th)
Rule('synthesize_HH_2_3', hh_2() >> hh_2() + HH_2_3(), H_HH_6th)
Rule('synthesize_HH_2_4', hh_2() >> hh_2() + HH_2_4(), H_HH_6th)
Rule('synthesize_HH_2_5', hh_2() >> hh_2() + HH_2_5(), H_HH_6th)
Rule('synthesize_HH_2_6', hh_2() >> hh_2() + HH_2_6(), H_HH_6th)
Rule('synthesize_HH_3_1', hh_3() >> hh_3() + HH_3_1(), H_HH_6th)
Rule('synthesize_HH_3_2', hh_3() >> hh_3() + HH_3_2(), H_HH_6th)
Rule('synthesize_HH_3_3', hh_3() >> hh_3() + HH_3_3(), H_HH_6th)
Rule('synthesize_HH_3_4', hh_3() >> hh_3() + HH_3_4(), H_HH_6th)
Rule('synthesize_HH_3_5', hh_3() >> hh_3() + HH_3_5(), H_HH_6th)
Rule('synthesize_HH_3_6', hh_3() >> hh_3() + HH_3_6(), H_HH_6th)
Rule('synthesize_HH_4_1', hh_4() >> hh_4() + HH_4_1(), H_HH_6th)
Rule('synthesize_HH_4_2', hh_4() >> hh_4() + HH_4_2(), H_HH_6th)
Rule('synthesize_HH_4_3', hh_4() >> hh_4() + HH_4_3(), H_HH_6th)
Rule('synthesize_HH_4_4', hh_4() >> hh_4() + HH_4_4(), H_HH_6th)
Rule('synthesize_HH_4_5', hh_4() >> hh_4() + HH_4_5(), H_HH_6th)
Rule('synthesize_HH_4_6', hh_4() >> hh_4() + HH_4_6(), H_HH_6th)

Rule('degrade_HH_1_1', HH_1_1() >> None, H_HH)
Rule('degrade_HH_1_2', HH_1_2() >> None, H_HH)
Rule('degrade_HH_1_3', HH_1_3() >> None, H_HH)
Rule('degrade_HH_1_4', HH_1_4() >> None, H_HH)
Rule('degrade_HH_1_5', HH_1_5() >> None, H_HH)
Rule('degrade_HH_1_6', HH_1_6() >> None, H_HH)
Rule('degrade_HH_2_1', HH_2_1() >> None, H_HH)
Rule('degrade_HH_2_2', HH_2_2() >> None, H_HH)
Rule('degrade_HH_2_3', HH_2_3() >> None, H_HH)
Rule('degrade_HH_2_4', HH_2_4() >> None, H_HH)
Rule('degrade_HH_2_5', HH_2_5() >> None, H_HH)
Rule('degrade_HH_2_6', HH_2_6() >> None, H_HH)
Rule('degrade_HH_3_1', HH_3_1() >> None, H_HH)
Rule('degrade_HH_3_2', HH_3_2() >> None, H_HH)
Rule('degrade_HH_3_3', HH_3_3() >> None, H_HH)
Rule('degrade_HH_3_4', HH_3_4() >> None, H_HH)
Rule('degrade_HH_3_5', HH_3_5() >> None, H_HH)
Rule('degrade_HH_3_6', HH_3_6() >> None, H_HH)
Rule('degrade_HH_4_1', HH_4_1() >> None, H_HH)
Rule('degrade_HH_4_2', HH_4_2() >> None, H_HH)
Rule('degrade_HH_4_3', HH_4_3() >> None, H_HH)
Rule('degrade_HH_4_4', HH_4_4() >> None, H_HH)
Rule('degrade_HH_4_5', HH_4_5() >> None, H_HH)
Rule('degrade_HH_4_6', HH_4_6() >> None, H_HH)

# complexation: re-dimensionalization will allow for simplification of the second order equations involving PTC, HH, and PH 

Expression('HH_1_1_2nd_order', K_PTC_HH*max_PTC*PTC_1_4_obs) #*HH_1_1_obs)
Expression('HH_1_2_2nd_order', K_PTC_HH*max_PTC*PTC_2_5_obs) #*HH_1_2_obs)
Expression('HH_1_3_2nd_order', K_PTC_HH*max_PTC*PTC_2_6_obs) #*HH_1_3_obs)
Expression('HH_1_4_2nd_order', K_PTC_HH*max_PTC*PTC_1_1_obs) #*HH_1_4_obs)
Expression('HH_1_5_2nd_order', K_PTC_HH*max_PTC*PTC_4_2_obs) #*HH_1_5_obs)
Expression('HH_1_6_2nd_order', K_PTC_HH*max_PTC*PTC_4_3_obs) #*HH_1_6_obs)
Expression('HH_2_1_2nd_order', K_PTC_HH*max_PTC*PTC_2_4_obs) #*HH_2_1_obs)
Expression('HH_2_2_2nd_order', K_PTC_HH*max_PTC*PTC_3_5_obs) #*HH_2_2_obs)
Expression('HH_2_3_2nd_order', K_PTC_HH*max_PTC*PTC_3_6_obs) #*HH_2_3_obs)
Expression('HH_2_4_2nd_order', K_PTC_HH*max_PTC*PTC_2_1_obs) #*HH_2_4_obs)
Expression('HH_2_5_2nd_order', K_PTC_HH*max_PTC*PTC_1_2_obs) #*HH_2_5_obs)
Expression('HH_2_6_2nd_order', K_PTC_HH*max_PTC*PTC_1_3_obs) #*HH_2_6_obs)
Expression('HH_3_1_2nd_order', K_PTC_HH*max_PTC*PTC_3_4_obs) #*HH_3_1_obs)
Expression('HH_3_2_2nd_order', K_PTC_HH*max_PTC*PTC_4_5_obs) #*HH_3_2_obs)
Expression('HH_3_3_2nd_order', K_PTC_HH*max_PTC*PTC_4_6_obs) #*HH_3_3_obs)
Expression('HH_3_4_2nd_order', K_PTC_HH*max_PTC*PTC_3_1_obs) #*HH_3_4_obs)
Expression('HH_3_5_2nd_order', K_PTC_HH*max_PTC*PTC_2_2_obs) #*HH_3_5_obs)
Expression('HH_3_6_2nd_order', K_PTC_HH*max_PTC*PTC_2_3_obs) #*HH_3_6_obs)
Expression('HH_4_1_2nd_order', K_PTC_HH*max_PTC*PTC_4_4_obs) #*HH_4_1_obs)
Expression('HH_4_2_2nd_order', K_PTC_HH*max_PTC*PTC_1_5_obs) #*HH_4_2_obs)
Expression('HH_4_3_2nd_order', K_PTC_HH*max_PTC*PTC_1_6_obs) #*HH_4_3_obs)
Expression('HH_4_4_2nd_order', K_PTC_HH*max_PTC*PTC_4_1_obs) #*HH_4_4_obs)
Expression('HH_4_5_2nd_order', K_PTC_HH*max_PTC*PTC_3_2_obs) #*HH_4_5_obs)
Expression('HH_4_6_2nd_order', K_PTC_HH*max_PTC*PTC_3_3_obs) #*HH_4_6_obs)

#===============================================================================
# Expression('HH_1_1_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_1_4_obs*HH_1_1_obs"))
# Expression('HH_1_2_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_2_5_obs*HH_1_2_obs"))
# Expression('HH_1_3_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_2_6_obs*HH_1_3_obs"))
# Expression('HH_1_4_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_1_1_obs*HH_1_4_obs"))
# Expression('HH_1_5_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_4_2_obs*HH_1_5_obs"))
# Expression('HH_1_6_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_4_3_obs*HH_1_6_obs"))
# Expression('HH_2_1_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_2_4_obs*HH_2_1_obs"))
# Expression('HH_2_2_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_3_5_obs*HH_2_2_obs"))
# Expression('HH_2_3_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_3_6_obs*HH_2_3_obs"))
# Expression('HH_2_4_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_2_1_obs*HH_2_4_obs"))
# Expression('HH_2_5_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_1_2_obs*HH_2_5_obs"))
# Expression('HH_2_6_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_1_3_obs*HH_2_6_obs"))
# Expression('HH_3_1_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_3_4_obs*HH_3_1_obs"))
# Expression('HH_3_2_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_4_5_obs*HH_3_2_obs"))
# Expression('HH_3_3_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_4_6_obs*HH_3_3_obs"))
# Expression('HH_3_4_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_3_1_obs*HH_3_4_obs"))
# Expression('HH_3_5_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_2_2_obs*HH_3_5_obs"))
# Expression('HH_3_6_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_2_3_obs*HH_3_6_obs"))
# Expression('HH_4_1_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_4_4_obs*HH_4_1_obs"))
# Expression('HH_4_2_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_1_5_obs*HH_4_2_obs"))
# Expression('HH_4_3_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_1_6_obs*HH_4_3_obs"))
# Expression('HH_4_4_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_4_1_obs*HH_4_4_obs"))
# Expression('HH_4_5_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_3_2_obs*HH_4_5_obs"))
# Expression('HH_4_6_2nd_order', sympify("K_PTC_HH*max_PTC*PTC_3_3_obs*HH_4_6_obs"))
#===============================================================================

Rule('HH_to_PH_1_1', HH_1_1() >> None, HH_1_1_2nd_order)
Rule('HH_to_PH_1_2', HH_1_2() >> None, HH_1_2_2nd_order)
Rule('HH_to_PH_1_3', HH_1_3() >> None, HH_1_3_2nd_order)
Rule('HH_to_PH_1_4', HH_1_4() >> None, HH_1_4_2nd_order)
Rule('HH_to_PH_1_5', HH_1_5() >> None, HH_1_5_2nd_order)
Rule('HH_to_PH_1_6', HH_1_6() >> None, HH_1_6_2nd_order)
Rule('HH_to_PH_2_1', HH_2_1() >> None, HH_2_1_2nd_order)
Rule('HH_to_PH_2_2', HH_2_2() >> None, HH_2_2_2nd_order)
Rule('HH_to_PH_2_3', HH_2_3() >> None, HH_2_3_2nd_order)
Rule('HH_to_PH_2_4', HH_2_4() >> None, HH_2_4_2nd_order)
Rule('HH_to_PH_2_5', HH_2_5() >> None, HH_2_5_2nd_order)
Rule('HH_to_PH_2_6', HH_2_6() >> None, HH_2_6_2nd_order)
Rule('HH_to_PH_3_1', HH_3_1() >> None, HH_3_1_2nd_order)
Rule('HH_to_PH_3_2', HH_3_2() >> None, HH_3_2_2nd_order)
Rule('HH_to_PH_3_3', HH_3_3() >> None, HH_3_3_2nd_order)
Rule('HH_to_PH_3_4', HH_3_4() >> None, HH_3_4_2nd_order)
Rule('HH_to_PH_3_5', HH_3_5() >> None, HH_3_5_2nd_order)
Rule('HH_to_PH_3_6', HH_3_6() >> None, HH_3_6_2nd_order)
Rule('HH_to_PH_4_1', HH_4_1() >> None, HH_4_1_2nd_order)
Rule('HH_to_PH_4_2', HH_4_2() >> None, HH_4_2_2nd_order)
Rule('HH_to_PH_4_3', HH_4_3() >> None, HH_4_3_2nd_order)
Rule('HH_to_PH_4_4', HH_4_4() >> None, HH_4_4_2nd_order)
Rule('HH_to_PH_4_5', HH_4_5() >> None, HH_4_5_2nd_order)
Rule('HH_to_PH_4_6', HH_4_6() >> None, HH_4_6_2nd_order)

# diffusion between faces: around the perimeter

Rule('diffuse_HH_1_1_2', HH_1_1() | HH_1_2(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_1_2_3', HH_1_2() | HH_1_3(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_1_3_4', HH_1_3() | HH_1_4(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_1_4_5', HH_1_4() | HH_1_5(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_1_5_6', HH_1_5() | HH_1_6(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_1_6_1', HH_1_6() | HH_1_1(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_2_1_2', HH_2_1() | HH_2_2(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_2_2_3', HH_2_2() | HH_2_3(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_2_3_4', HH_2_3() | HH_2_4(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_2_4_5', HH_2_4() | HH_2_5(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_2_5_6', HH_2_5() | HH_2_6(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_2_6_1', HH_2_6() | HH_2_1(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_3_1_2', HH_3_1() | HH_3_2(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_3_2_3', HH_3_2() | HH_3_3(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_3_3_4', HH_3_3() | HH_3_4(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_3_4_5', HH_3_4() | HH_3_5(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_3_5_6', HH_3_5() | HH_3_6(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_3_6_1', HH_3_6() | HH_3_1(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_4_1_2', HH_4_1() | HH_4_2(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_4_2_3', HH_4_2() | HH_4_3(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_4_3_4', HH_4_3() | HH_4_4(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_4_4_5', HH_4_4() | HH_4_5(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_4_5_6', HH_4_5() | HH_4_6(), LMxfer_HH, LMxfer_HH)
Rule('diffuse_HH_4_6_1', HH_4_6() | HH_4_1(), LMxfer_HH, LMxfer_HH)

#### PTC-HH complex (PH)

# complexation: re-dimensionalization will allow for simplification of the second order equations involving PTC, HH, and PH 

Expression('PH_1_1_2nd_order', K_PTC_HH*max_HH*HH_1_4_obs*PTC_1_1_obs)
Expression('PH_1_2_2nd_order', K_PTC_HH*max_HH*HH_2_5_obs*PTC_1_2_obs)
Expression('PH_1_3_2nd_order', K_PTC_HH*max_HH*HH_2_6_obs*PTC_1_3_obs)
Expression('PH_1_4_2nd_order', K_PTC_HH*max_HH*HH_1_1_obs*PTC_1_4_obs)
Expression('PH_1_5_2nd_order', K_PTC_HH*max_HH*HH_4_2_obs*PTC_1_5_obs)
Expression('PH_1_6_2nd_order', K_PTC_HH*max_HH*HH_4_3_obs*PTC_1_6_obs)
Expression('PH_2_1_2nd_order', K_PTC_HH*max_HH*HH_2_4_obs*PTC_2_1_obs)
Expression('PH_2_2_2nd_order', K_PTC_HH*max_HH*HH_3_5_obs*PTC_2_2_obs)
Expression('PH_2_3_2nd_order', K_PTC_HH*max_HH*HH_3_6_obs*PTC_2_3_obs)
Expression('PH_2_4_2nd_order', K_PTC_HH*max_HH*HH_2_1_obs*PTC_2_4_obs)
Expression('PH_2_5_2nd_order', K_PTC_HH*max_HH*HH_1_2_obs*PTC_2_5_obs)
Expression('PH_2_6_2nd_order', K_PTC_HH*max_HH*HH_1_3_obs*PTC_2_6_obs)
Expression('PH_3_1_2nd_order', K_PTC_HH*max_HH*HH_3_4_obs*PTC_3_1_obs)
Expression('PH_3_2_2nd_order', K_PTC_HH*max_HH*HH_4_5_obs*PTC_3_2_obs)
Expression('PH_3_3_2nd_order', K_PTC_HH*max_HH*HH_4_6_obs*PTC_3_3_obs)
Expression('PH_3_4_2nd_order', K_PTC_HH*max_HH*HH_3_1_obs*PTC_3_4_obs)
Expression('PH_3_5_2nd_order', K_PTC_HH*max_HH*HH_2_2_obs*PTC_3_5_obs)
Expression('PH_3_6_2nd_order', K_PTC_HH*max_HH*HH_2_3_obs*PTC_3_6_obs)
Expression('PH_4_1_2nd_order', K_PTC_HH*max_HH*HH_4_4_obs*PTC_4_1_obs)
Expression('PH_4_2_2nd_order', K_PTC_HH*max_HH*HH_1_5_obs*PTC_4_2_obs)
Expression('PH_4_3_2nd_order', K_PTC_HH*max_HH*HH_1_6_obs*PTC_4_3_obs)
Expression('PH_4_4_2nd_order', K_PTC_HH*max_HH*HH_4_1_obs*PTC_4_4_obs)
Expression('PH_4_5_2nd_order', K_PTC_HH*max_HH*HH_3_2_obs*PTC_4_5_obs)
Expression('PH_4_6_2nd_order', K_PTC_HH*max_HH*HH_3_3_obs*PTC_4_6_obs)

Rule('PH_complex_1_1', None >> PH_1_1(), PH_1_1_2nd_order)
Rule('PH_complex_1_2', None >> PH_1_2(), PH_1_2_2nd_order)
Rule('PH_complex_1_3', None >> PH_1_3(), PH_1_3_2nd_order)
Rule('PH_complex_1_4', None >> PH_1_4(), PH_1_4_2nd_order)
Rule('PH_complex_1_5', None >> PH_1_5(), PH_1_5_2nd_order)
Rule('PH_complex_1_6', None >> PH_1_6(), PH_1_6_2nd_order)
Rule('PH_complex_2_1', None >> PH_2_1(), PH_2_1_2nd_order)
Rule('PH_complex_2_2', None >> PH_2_2(), PH_2_2_2nd_order)
Rule('PH_complex_2_3', None >> PH_2_3(), PH_2_3_2nd_order)
Rule('PH_complex_2_4', None >> PH_2_4(), PH_2_4_2nd_order)
Rule('PH_complex_2_5', None >> PH_2_5(), PH_2_5_2nd_order)
Rule('PH_complex_2_6', None >> PH_2_6(), PH_2_6_2nd_order)
Rule('PH_complex_3_1', None >> PH_3_1(), PH_3_1_2nd_order)
Rule('PH_complex_3_2', None >> PH_3_2(), PH_3_2_2nd_order)
Rule('PH_complex_3_3', None >> PH_3_3(), PH_3_3_2nd_order)
Rule('PH_complex_3_4', None >> PH_3_4(), PH_3_4_2nd_order)
Rule('PH_complex_3_5', None >> PH_3_5(), PH_3_5_2nd_order)
Rule('PH_complex_3_6', None >> PH_3_6(), PH_3_6_2nd_order)
Rule('PH_complex_4_1', None >> PH_4_1(), PH_4_1_2nd_order)
Rule('PH_complex_4_2', None >> PH_4_2(), PH_4_2_2nd_order)
Rule('PH_complex_4_3', None >> PH_4_3(), PH_4_3_2nd_order)
Rule('PH_complex_4_4', None >> PH_4_4(), PH_4_4_2nd_order)
Rule('PH_complex_4_5', None >> PH_4_5(), PH_4_5_2nd_order)
Rule('PH_complex_4_6', None >> PH_4_6(), PH_4_6_2nd_order)

# degradation

Rule('degrade_PH_1_1', PH_1_1() >> None, H_PH)
Rule('degrade_PH_1_2', PH_1_2() >> None, H_PH)
Rule('degrade_PH_1_3', PH_1_3() >> None, H_PH)
Rule('degrade_PH_1_4', PH_1_4() >> None, H_PH)
Rule('degrade_PH_1_5', PH_1_5() >> None, H_PH)
Rule('degrade_PH_1_6', PH_1_6() >> None, H_PH)
Rule('degrade_PH_2_1', PH_2_1() >> None, H_PH)
Rule('degrade_PH_2_2', PH_2_2() >> None, H_PH)
Rule('degrade_PH_2_3', PH_2_3() >> None, H_PH)
Rule('degrade_PH_2_4', PH_2_4() >> None, H_PH)
Rule('degrade_PH_2_5', PH_2_5() >> None, H_PH)
Rule('degrade_PH_2_6', PH_2_6() >> None, H_PH)
Rule('degrade_PH_3_1', PH_3_1() >> None, H_PH)
Rule('degrade_PH_3_2', PH_3_2() >> None, H_PH)
Rule('degrade_PH_3_3', PH_3_3() >> None, H_PH)
Rule('degrade_PH_3_4', PH_3_4() >> None, H_PH)
Rule('degrade_PH_3_5', PH_3_5() >> None, H_PH)
Rule('degrade_PH_3_6', PH_3_6() >> None, H_PH)
Rule('degrade_PH_4_1', PH_4_1() >> None, H_PH)
Rule('degrade_PH_4_2', PH_4_2() >> None, H_PH)
Rule('degrade_PH_4_3', PH_4_3() >> None, H_PH)
Rule('degrade_PH_4_4', PH_4_4() >> None, H_PH)
Rule('degrade_PH_4_5', PH_4_5() >> None, H_PH)
Rule('degrade_PH_4_6', PH_4_6() >> None, H_PH)

#### cubitus interruptus mRNA (ci)

# mistakes
#===============================================================================
# Expression('Hill_ENci_1', K_ENci**nu_ENci/(K_ENci**nu_ENci + CN_1_obs**nu_ENci))
# Expression('Hill_ENci_2', K_ENci**nu_ENci/(K_ENci**nu_ENci + CN_2_obs**nu_ENci))
# Expression('Hill_ENci_3', K_ENci**nu_ENci/(K_ENci**nu_ENci + CN_3_obs**nu_ENci))
# Expression('Hill_ENci_4', K_ENci**nu_ENci/(K_ENci**nu_ENci + CN_4_obs**nu_ENci))
# 
# Expression('Hill_Bci_1', H_ci*CI_1_obs*Hill_ENci_1**nu_Bci/(K_Bci**nu_Bci + CI_1_obs*Hill_ENci_1**nu_Bci))
# Expression('Hill_Bci_2', H_ci*CI_2_obs*Hill_ENci_2**nu_Bci/(K_Bci**nu_Bci + CI_2_obs*Hill_ENci_2**nu_Bci))
# Expression('Hill_Bci_3', H_ci*CI_3_obs*Hill_ENci_3**nu_Bci/(K_Bci**nu_Bci + CI_3_obs*Hill_ENci_3**nu_Bci))
# Expression('Hill_Bci_4', H_ci*CI_4_obs*Hill_ENci_4**nu_Bci/(K_Bci**nu_Bci + CI_4_obs*Hill_ENci_4**nu_Bci))
#===============================================================================

Expression('Hill_ENci_1', K_ENci**nu_ENci/(K_ENci**nu_ENci + EN_1_obs**nu_ENci))
Expression('Hill_ENci_2', K_ENci**nu_ENci/(K_ENci**nu_ENci + EN_2_obs**nu_ENci))
Expression('Hill_ENci_3', K_ENci**nu_ENci/(K_ENci**nu_ENci + EN_3_obs**nu_ENci))
Expression('Hill_ENci_4', K_ENci**nu_ENci/(K_ENci**nu_ENci + EN_4_obs**nu_ENci))
  
Expression('Hill_Bci_1', H_ci*(B*Hill_ENci_1)**nu_Bci/(K_Bci**nu_Bci + (B*Hill_ENci_1)**nu_Bci))
Expression('Hill_Bci_2', H_ci*(B*Hill_ENci_2)**nu_Bci/(K_Bci**nu_Bci + (B*Hill_ENci_2)**nu_Bci))
Expression('Hill_Bci_3', H_ci*(B*Hill_ENci_3)**nu_Bci/(K_Bci**nu_Bci + (B*Hill_ENci_3)**nu_Bci))
Expression('Hill_Bci_4', H_ci*(B*Hill_ENci_4)**nu_Bci/(K_Bci**nu_Bci + (B*Hill_ENci_4)**nu_Bci))

#===============================================================================
# Expression('Hill_Bci_1', sympify("H_ci*B*(K_ENci**nu_ENci/(K_ENci**nu_ENci + EN_1_obs**nu_ENci))**nu_Bci/(K_Bci**nu_Bci + B*(K_ENci**nu_ENci/(K_ENci**nu_ENci + EN_1_obs**nu_ENci))**nu_Bci)"))
# Expression('Hill_Bci_2', sympify("H_ci*B*(K_ENci**nu_ENci/(K_ENci**nu_ENci + EN_2_obs**nu_ENci))**nu_Bci/(K_Bci**nu_Bci + B*(K_ENci**nu_ENci/(K_ENci**nu_ENci + EN_2_obs**nu_ENci))**nu_Bci)"))
# Expression('Hill_Bci_3', sympify("H_ci*B*(K_ENci**nu_ENci/(K_ENci**nu_ENci + EN_3_obs**nu_ENci))**nu_Bci/(K_Bci**nu_Bci + B*(K_ENci**nu_ENci/(K_ENci**nu_ENci + EN_3_obs**nu_ENci))**nu_Bci)"))
# Expression('Hill_Bci_4', sympify("H_ci*B*(K_ENci**nu_ENci/(K_ENci**nu_ENci + EN_4_obs**nu_ENci))**nu_Bci/(K_Bci**nu_Bci + B*(K_ENci**nu_ENci/(K_ENci**nu_ENci + EN_4_obs**nu_ENci))**nu_Bci)"))
#===============================================================================

Rule('synthesize_ci_1', None >> ci_1(), Hill_Bci_1)
Rule('synthesize_ci_2', None >> ci_2(), Hill_Bci_2)
Rule('synthesize_ci_3', None >> ci_3(), Hill_Bci_3)
Rule('synthesize_ci_4', None >> ci_4(), Hill_Bci_4)

Rule('degrade_ci_1', ci_1() >> None, H_ci)
Rule('degrade_ci_2', ci_2() >> None, H_ci)
Rule('degrade_ci_3', ci_3() >> None, H_ci)
Rule('degrade_ci_4', ci_4() >> None, H_ci)

#### cubitus interruptus protein (CI) and protein fragment (CN)

# synthesis (CI)

Rule('synthesize_CI_1', ci_1() >> ci_1() + CI_1(), H_CI)
Rule('synthesize_CI_2', ci_2() >> ci_2() + CI_2(), H_CI)
Rule('synthesize_CI_3', ci_3() >> ci_3() + CI_3(), H_CI)
Rule('synthesize_CI_4', ci_4() >> ci_4() + CI_4(), H_CI)

# degradation (CI)

Rule('degrade_CI_1', CI_1() >> None, H_CI)
Rule('degrade_CI_2', CI_2() >> None, H_CI)
Rule('degrade_CI_3', CI_3() >> None, H_CI)
Rule('degrade_CI_4', CI_4() >> None, H_CI)

# degradation (CN)

Rule('degrade_CN_1', CN_1() >> None, H_CN) #H_CI)
Rule('degrade_CN_2', CN_2() >> None, H_CN) #H_CI)
Rule('degrade_CN_3', CN_3() >> None, H_CN) #H_CI)
Rule('degrade_CN_4', CN_4() >> None, H_CN) #H_CI)

# cleavage (CI -> CN)

Expression('PTC_iT_1', PTC_1_1_obs + PTC_1_2_obs + PTC_1_3_obs + PTC_1_4_obs + PTC_1_5_obs + PTC_1_6_obs)
Expression('PTC_iT_2', PTC_2_1_obs + PTC_2_2_obs + PTC_2_3_obs + PTC_2_4_obs + PTC_2_5_obs + PTC_2_6_obs)
Expression('PTC_iT_3', PTC_3_1_obs + PTC_3_2_obs + PTC_3_3_obs + PTC_3_4_obs + PTC_3_5_obs + PTC_3_6_obs)
Expression('PTC_iT_4', PTC_4_1_obs + PTC_4_2_obs + PTC_4_3_obs + PTC_4_4_obs + PTC_4_5_obs + PTC_4_6_obs)
 
Expression('Hill_PTCci_1', (C_CI*PTC_iT_1**nu_PTCCI)/(K_PTCCI**nu_PTCCI + PTC_iT_1**nu_PTCCI))
Expression('Hill_PTCci_2', (C_CI*PTC_iT_2**nu_PTCCI)/(K_PTCCI**nu_PTCCI + PTC_iT_2**nu_PTCCI))
Expression('Hill_PTCci_3', (C_CI*PTC_iT_3**nu_PTCCI)/(K_PTCCI**nu_PTCCI + PTC_iT_3**nu_PTCCI))
Expression('Hill_PTCci_4', (C_CI*PTC_iT_4**nu_PTCCI)/(K_PTCCI**nu_PTCCI + PTC_iT_4**nu_PTCCI))

#===============================================================================
# Expression('Hill_PTCci_1', sympify("(C_CI*(PTC_1_1_obs + PTC_1_2_obs + PTC_1_3_obs + PTC_1_4_obs + PTC_1_5_obs + PTC_1_6_obs)**nu_PTCCI)/(K_PTCCI**nu_PTCCI + (PTC_1_1_obs + PTC_1_2_obs + PTC_1_3_obs + PTC_1_4_obs + PTC_1_5_obs + PTC_1_6_obs)**nu_PTCCI)"))
# Expression('Hill_PTCci_2', sympify("(C_CI*(PTC_2_1_obs + PTC_2_2_obs + PTC_2_3_obs + PTC_2_4_obs + PTC_2_5_obs + PTC_2_6_obs)**nu_PTCCI)/(K_PTCCI**nu_PTCCI + (PTC_2_1_obs + PTC_2_2_obs + PTC_2_3_obs + PTC_2_4_obs + PTC_2_5_obs + PTC_2_6_obs)**nu_PTCCI)"))
# Expression('Hill_PTCci_3', sympify("(C_CI*(PTC_3_1_obs + PTC_3_2_obs + PTC_3_3_obs + PTC_3_4_obs + PTC_3_5_obs + PTC_3_6_obs)**nu_PTCCI)/(K_PTCCI**nu_PTCCI + (PTC_3_1_obs + PTC_3_2_obs + PTC_3_3_obs + PTC_3_4_obs + PTC_3_5_obs + PTC_3_6_obs)**nu_PTCCI)"))
# Expression('Hill_PTCci_4', sympify("(C_CI*(PTC_4_1_obs + PTC_4_2_obs + PTC_4_3_obs + PTC_4_4_obs + PTC_4_5_obs + PTC_4_6_obs)**nu_PTCCI)/(K_PTCCI**nu_PTCCI + (PTC_4_1_obs + PTC_4_2_obs + PTC_4_3_obs + PTC_4_4_obs + PTC_4_5_obs + PTC_4_6_obs)**nu_PTCCI)"))
#===============================================================================

Rule('CI_cleavage_1', CI_1() >> CN_1(), Hill_PTCci_1)
Rule('CI_cleavage_2', CI_2() >> CN_2(), Hill_PTCci_2)
Rule('CI_cleavage_3', CI_3() >> CN_3(), Hill_PTCci_3)
Rule('CI_cleavage_4', CI_4() >> CN_4(), Hill_PTCci_4)

